import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Northstar Workspace",
    "description": "Northstar Workspace",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-001",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-001",
    "asset_type": "image",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://northstar.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Harbor Workspace",
    "description": "Harbor Workspace",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-002",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-002",
    "asset_type": "video",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://harbor.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Cedar Workspace",
    "description": "Cedar Workspace",
    "placeholder": "",
    "status": "available",
    "state_history": [
      {
        "from": null,
        "to": "available",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-003",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-003",
    "asset_type": "audio",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://cedar.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Summit Workspace",
    "description": "Summit Workspace",
    "placeholder": "",
    "status": "deprecated",
    "state_history": [
      {
        "from": null,
        "to": "deprecated",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-004",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-004",
    "asset_type": "document",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://summit.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Orchard Workspace",
    "description": "Orchard Workspace",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-005",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-005",
    "asset_type": "image",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://orchard.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Willow Workspace",
    "description": "Willow Workspace",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-006",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-006",
    "asset_type": "video",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://willow.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Atlas Workspace",
    "description": "Atlas Workspace",
    "placeholder": "",
    "status": "available",
    "state_history": [
      {
        "from": null,
        "to": "available",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-007",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-007",
    "asset_type": "audio",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://atlas.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Meadow Workspace",
    "description": "Meadow Workspace",
    "placeholder": "",
    "status": "deprecated",
    "state_history": [
      {
        "from": null,
        "to": "deprecated",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-008",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-008",
    "asset_type": "document",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://meadow.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Juniper Workspace",
    "description": "Juniper Workspace",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-009",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-009",
    "asset_type": "image",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://juniper.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Brook Workspace",
    "description": "Brook Workspace",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-010",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-010",
    "asset_type": "video",
    "mime_type": "Mime Type",
    "storage_bucket": "Storage Bucket",
    "object_key": "Object Key",
    "source_url": "https://brook.example.com/source",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  }
];
