import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Anika Bhatt",
    "description": "Anika Bhatt",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-001",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-001",
    "name": "Anika Bhatt",
    "primary_topic": "ai_research",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 1,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Milo Chen",
    "description": "Milo Chen",
    "placeholder": "",
    "status": "tracked_unfeeded",
    "state_history": [
      {
        "from": null,
        "to": "tracked_unfeeded",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-002",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-002",
    "name": "Milo Chen",
    "primary_topic": "design",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 2,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Sunny Rivera",
    "description": "Sunny Rivera",
    "placeholder": "",
    "status": "dormant",
    "state_history": [
      {
        "from": null,
        "to": "dormant",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-003",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-003",
    "name": "Sunny Rivera",
    "primary_topic": "ai_engineering",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 3,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Ada Morgan",
    "description": "Ada Morgan",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-004",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-004",
    "name": "Ada Morgan",
    "primary_topic": "writers",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 4,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Theo Reed",
    "description": "Theo Reed",
    "placeholder": "",
    "status": "tracked_unfeeded",
    "state_history": [
      {
        "from": null,
        "to": "tracked_unfeeded",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-005",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-005",
    "name": "Theo Reed",
    "primary_topic": "meaning_layer",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 5,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Lena Park",
    "description": "Lena Park",
    "placeholder": "",
    "status": "dormant",
    "state_history": [
      {
        "from": null,
        "to": "dormant",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-006",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-006",
    "name": "Lena Park",
    "primary_topic": "founders",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 6,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Sam Brooks",
    "description": "Sam Brooks",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-007",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-007",
    "name": "Sam Brooks",
    "primary_topic": "other",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 7,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Nora Patel",
    "description": "Nora Patel",
    "placeholder": "",
    "status": "tracked_unfeeded",
    "state_history": [
      {
        "from": null,
        "to": "tracked_unfeeded",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-008",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-008",
    "name": "Nora Patel",
    "primary_topic": "product",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 8,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Eli Stone",
    "description": "Eli Stone",
    "placeholder": "",
    "status": "dormant",
    "state_history": [
      {
        "from": null,
        "to": "dormant",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-009",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-009",
    "name": "Eli Stone",
    "primary_topic": "ai_research",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 9,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  },
  {
    "label": "Maya Silva",
    "description": "Maya Silva",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-010",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "person_id": "person-010",
    "name": "Maya Silva",
    "primary_topic": "design",
    "role": "",
    "org": "",
    "x_handle": "",
    "blurb": "",
    "article_count": 10,
    "window_days": 0,
    "articles": [],
    "top_clusters": [],
    "co_talkers": []
  }
];
