import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "plan_code": "northstar_001",
    "plan_name": "Northstar Plan",
    "billing_interval": "monthly",
    "interval_count": 1,
    "amount_minor": 1900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 1900,
    "projected_overage_minor": 1900,
    "samples": [],
    "owner_id": "owner-001",
    "owner_type": "organization",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-001",
    "product_family": "Product Family",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "harbor_002",
    "plan_name": "Harbor Plan",
    "billing_interval": "quarterly",
    "interval_count": 1,
    "amount_minor": 4900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 4900,
    "projected_overage_minor": 4900,
    "samples": [],
    "owner_id": "owner-002",
    "owner_type": "team",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-002",
    "product_family": "Product Family",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "cedar_003",
    "plan_name": "Cedar Plan",
    "billing_interval": "annual",
    "interval_count": 1,
    "amount_minor": 9900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 9900,
    "projected_overage_minor": 9900,
    "samples": [],
    "owner_id": "owner-003",
    "owner_type": "user",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-003",
    "product_family": "Product Family",
    "status": "private_beta",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "summit_004",
    "plan_name": "Summit Plan",
    "billing_interval": "monthly",
    "interval_count": 1,
    "amount_minor": 14900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 14900,
    "projected_overage_minor": 14900,
    "samples": [],
    "owner_id": "owner-004",
    "owner_type": "organization",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-004",
    "product_family": "Product Family",
    "status": "legacy",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "orchard_005",
    "plan_name": "Orchard Plan",
    "billing_interval": "quarterly",
    "interval_count": 1,
    "amount_minor": 24900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 24900,
    "projected_overage_minor": 24900,
    "samples": [],
    "owner_id": "owner-005",
    "owner_type": "team",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-005",
    "product_family": "Product Family",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "willow_006",
    "plan_name": "Willow Plan",
    "billing_interval": "annual",
    "interval_count": 1,
    "amount_minor": 1900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 1900,
    "projected_overage_minor": 1900,
    "samples": [],
    "owner_id": "owner-006",
    "owner_type": "user",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-006",
    "product_family": "Product Family",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "atlas_007",
    "plan_name": "Atlas Plan",
    "billing_interval": "monthly",
    "interval_count": 1,
    "amount_minor": 4900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 4900,
    "projected_overage_minor": 4900,
    "samples": [],
    "owner_id": "owner-007",
    "owner_type": "organization",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-007",
    "product_family": "Product Family",
    "status": "private_beta",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "meadow_008",
    "plan_name": "Meadow Plan",
    "billing_interval": "quarterly",
    "interval_count": 1,
    "amount_minor": 9900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 9900,
    "projected_overage_minor": 9900,
    "samples": [],
    "owner_id": "owner-008",
    "owner_type": "team",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-008",
    "product_family": "Product Family",
    "status": "legacy",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "juniper_009",
    "plan_name": "Juniper Plan",
    "billing_interval": "annual",
    "interval_count": 1,
    "amount_minor": 14900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 14900,
    "projected_overage_minor": 14900,
    "samples": [],
    "owner_id": "owner-009",
    "owner_type": "user",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-009",
    "product_family": "Product Family",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "brook_010",
    "plan_name": "Brook Plan",
    "billing_interval": "monthly",
    "interval_count": 1,
    "amount_minor": 24900,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "flat",
    "meter_name": "Meter Name",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "seats",
    "period_start": "2026-09-01",
    "period_end": "2026-09-01",
    "rollover_strategy": "none",
    "overage_rate_minor": 24900,
    "projected_overage_minor": 24900,
    "samples": [],
    "owner_id": "owner-010",
    "owner_type": "organization",
    "ownership_role": "",
    "ownership_transferred_at": "2026-09-01T12:00:00.000Z",
    "plan_id": "plan-010",
    "product_family": "Product Family",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  }
];
