import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Northstar Workspace",
    "description": "Northstar Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-001",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-001",
    "lead_title": "Lead Title",
    "lead_url": "https://northstar.example.com/lead",
    "lens": "entity",
    "member_count": 1,
    "member_people_count": 1,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Harbor Workspace",
    "description": "Harbor Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-002",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-002",
    "lead_title": "Lead Title",
    "lead_url": "https://harbor.example.com/lead",
    "lens": "semantic",
    "member_count": 2,
    "member_people_count": 2,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Cedar Workspace",
    "description": "Cedar Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-003",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-003",
    "lead_title": "Lead Title",
    "lead_url": "https://cedar.example.com/lead",
    "lens": "entity",
    "member_count": 3,
    "member_people_count": 3,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Summit Workspace",
    "description": "Summit Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-004",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-004",
    "lead_title": "Lead Title",
    "lead_url": "https://summit.example.com/lead",
    "lens": "semantic",
    "member_count": 4,
    "member_people_count": 4,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Orchard Workspace",
    "description": "Orchard Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-005",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-005",
    "lead_title": "Lead Title",
    "lead_url": "https://orchard.example.com/lead",
    "lens": "entity",
    "member_count": 5,
    "member_people_count": 5,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Willow Workspace",
    "description": "Willow Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-006",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-006",
    "lead_title": "Lead Title",
    "lead_url": "https://willow.example.com/lead",
    "lens": "semantic",
    "member_count": 6,
    "member_people_count": 6,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Atlas Workspace",
    "description": "Atlas Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-007",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-007",
    "lead_title": "Lead Title",
    "lead_url": "https://atlas.example.com/lead",
    "lens": "entity",
    "member_count": 7,
    "member_people_count": 7,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Meadow Workspace",
    "description": "Meadow Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-008",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-008",
    "lead_title": "Lead Title",
    "lead_url": "https://meadow.example.com/lead",
    "lens": "semantic",
    "member_count": 8,
    "member_people_count": 8,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Juniper Workspace",
    "description": "Juniper Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-009",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-009",
    "lead_title": "Lead Title",
    "lead_url": "https://juniper.example.com/lead",
    "lens": "entity",
    "member_count": 9,
    "member_people_count": 9,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  },
  {
    "label": "Brook Workspace",
    "description": "Brook Workspace",
    "placeholder": "",
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "updated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-010",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "cluster_id": "cluster-010",
    "lead_title": "Lead Title",
    "lead_url": "https://brook.example.com/lead",
    "lens": "semantic",
    "member_count": 10,
    "member_people_count": 10,
    "dominant_category": "",
    "is_trending": false,
    "window_days": 0,
    "max_similarity": 0,
    "mean_similarity": 0,
    "people": [],
    "members": []
  }
];
