import json,pathlib
r=pathlib.Path(__file__).resolve().parent
report=json.loads((r/'verification.json').read_text());rows=[]
for o in report['objects']:
 for f in report['frameworks']:
  before=json.loads((r/'before'/o/f/'craft.json').read_text())['views']
  after=json.loads((r/'after'/o/f/'craft.json').read_text())['views']
  label=lambda v:next((t['text'] for t in v['craft']['tabs'] if t['selected']=='true'),'Timeline')
  for a in after:
   b=next((b for b in before if (b['context'],b['theme'],b['width'],label(b))==(a['context'],a['theme'],a['width'],label(a))),None)
   rows.append({'object':o,'framework':f,'context':a['context'],'theme':a['theme'],'width':str(a['width']),'panel':label(a),'before':('before/'+b['output']+'/'+b['screenshot']) if b else None,'after':'after/'+a['output']+'/'+a['screenshot']})
html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>S198 M03 — detail and timeline review</title>
<style>body{font:16px system-ui;background:#14181d;color:#ebedef;margin:32px auto;max-width:1400px;padding:0 24px}h1{font-size:28px}p{line-height:1.5;color:#bdc5cd}nav{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}select{padding:8px;background:#242c35;color:inherit;border:1px solid #606870;border-radius:5px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.shot{background:#20262d;border:1px solid #49525d;padding:12px;max-height:900px;overflow:auto}img{display:block;width:100%;height:auto}a{color:#8dc7fc}small{display:block;color:#aeb8c3;margin-bottom:12px}@media(max-width:700px){.pair{grid-template-columns:1fr}}</style>
<h1>Detail and timeline — Sprint 198 M03</h1><p>132 accepted React/Vue views · 390 / 820 / 1440 · light and dark · 0 viewport overflow, errors, editable read fields, empty cards, or text differences. Built for review; builderSelfCertified: false.</p>
<p>Before: 8762d3768. After: 7bc0aebbc. Dark BEFORE views are root-theme-switch stress captures with light chart assets. AFTER dark views use artifacts generated for dark. Pixel attribution uses matching light views.</p>
<p><a href="verification.json">Verification and file attribution</a> · <a href="README.md">Item mapping and limits</a> · <a href="html/proof.json">HTML panel keyboard proof and owned action limit</a></p><nav id="controls"></nav><section class="pair"><article><h2>Before</h2><small id="before-label"></small><div class="shot"><a id="before-link"><img id="before-img"></a></div></article><article><h2>After</h2><small id="after-label"></small><div class="shot"><a id="after-link"><img id="after-img"></a></div></article></section>
<script>const rows=ROWS;const selected={object:'Subscription',framework:'react',context:'detail',theme:'light',width:'820',panel:'Details'};const selectors={};for(const key of Object.keys(selected)){const label=document.createElement('label');label.textContent=key+' ';const select=document.createElement('select');label.append(select);document.getElementById('controls').append(label);selectors[key]=select;select.onchange=()=>{selected[key]=select.value;update()}}function update(){for(const key of Object.keys(selected)){const values=[...new Set(rows.filter(row=>key!=='panel'||(row.object===selected.object&&row.context===selected.context)).map(row=>row[key]))];if(!values.includes(selected[key]))selected[key]=values[0];selectors[key].replaceChildren(...values.map(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===selected[key];return option}))}const row=rows.find(row=>Object.keys(selected).every(key=>row[key]===selected[key]));for(const phase of ['before','after']){const src=row?.[phase];document.getElementById(phase+'-img').src=src||'';document.getElementById(phase+'-img').alt=src?'Screenshot '+src:'No matching baseline panel';document.getElementById(phase+'-link').href=src||'#';document.getElementById(phase+'-label').textContent=src||'No matching baseline panel'}}update();</script>'''
(r/'index.html').write_text(html.replace('ROWS',json.dumps(rows)))
