export const model = {
  "allowedTransitions": [],
  "archiveMetadata": {},
  "archiveReason": "Consumer archive reason",
  "archivedAt": "Consumer archived at",
  "archivedBy": "Consumer archived by",
  "billingInterval": "Consumer billing interval",
  "cancelAtPeriodEnd": false,
  "cancellationReason": "Consumer cancellation reason",
  "cancellationReasonCode": "Consumer cancellation reason code",
  "cancellationRequestedAt": "2026-09-05T12:00:00.000Z",
  "channel": "online",
  "createdAt": "2026-09-05T12:00:00.000Z",
  "currency": "Consumer currency",
  "isArchived": false,
  "lastEvent": "Consumer last event",
  "lastEventAt": "2026-09-05T12:00:00.000Z",
  "occurredAt": "2026-09-05T12:00:00.000Z",
  "organizationId": "consumer-organization-id",
  "paymentMethod": "card",
  "paymentReference": "Consumer payment reference",
  "pricingModel": "Consumer pricing model",
  "restorationMetadata": {},
  "restoredAt": "Consumer restored at",
  "riskScore": 0,
  "stateHistory": [],
  "status": "Consumer status",
  "taxBehavior": "exclusive",
  "transactionId": "consumer-transaction-id",
  "unitAmountCents": 0,
  "updatedAt": "2026-09-05T12:00:00.000Z",
  "userId": "consumer-user-id"
};
