import assert from 'node:assert/strict';
import fs from 'node:fs';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {validateSprint188Timeout} from '../../../../../scripts/product-reality/s185-suite-accounting.mjs';
import {auditSprint188Timeout} from '../../../../../scripts/product-reality/s185-audit-closeout.mjs';
const base='artifacts/product-reality/sprint-188/m06';
const readBytes=file=>fs.readFileSync(file);
const read=file=>JSON.parse(readBytes(file));
const hash=bytes=>createHash('sha256').update(bytes).digest('hex');
const readHistorical=(head,file)=>execFileSync('git',['show',`${head}:${file}`],{maxBuffer:128*1024*1024});
const approval=read(`${base}/accepted-timeout/approval.json`);
const mission=read(`${base}/accepted-timeout/cmos-mission.json`);
const original=read(`${base}/cmos-mission-corrected.json`);
for (const index of [0,1,3,4,5]) assert.equal(mission.successCriteria[index],original.successCriteria[index]);
assert(mission.successCriteria[2].includes('one documented root-core mover-test timeout'));
assert(mission.successCriteria[2].includes('no other failed observation is excepted'));
assert.equal(read(`${base}/cmos-sprint.json`).status,'Active');
const carries=read(`${base}/carries-corrected.json`);assert.equal(carries.builderSelfCertified,false);assert.equal(carries.separateReviewRequired,true);
assert.equal(read(`${base}/final-proof-corrected/reconnect/notice-plan.json`).status,'prepared-unsent');
const accounting=read(`${base}/closeout/suite-accounting.json`);
const accepted=validateSprint188Timeout({approval,failures:accounting.closeoutFailures,executions:accounting.executions,readBytes,readHistorical});
const ref={path:`${base}/accepted-timeout/approval.json`,sha256:hash(readBytes(`${base}/accepted-timeout/approval.json`))};
accounting.closeoutFailures[0].status='approved-timeout-disclosed';accounting.closeoutFailures[0].approval=ref;
accounting.timeoutAcceptance={...accepted,approval:ref};
assert(auditSprint188Timeout({approval,accounting,readBytes,readHistorical}));
const output=`${base}/accepted-timeout/input-verification.json`;assert(!fs.existsSync(output));
fs.writeFileSync(output,JSON.stringify({status:'passed',head:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),decisionId:1830,accepted,captureRewritten:false,scope:'Approved exception, literal CMOS amendment, review follow-up and retained diagnostic; no capture replay.'},null,2)+'\n');
console.log('Decision1830 evidence verified by both implementations; only criterion3 amended; raw failure remains visible; sprint review pending.');
