import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Article 01",
    "description": "",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-001",
    "slug": "slug sample 1",
    "author_id": "",
    "content_type": "knowledge_base",
    "excerpt": "",
    "body_markdown": "body-markdown sample 1",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 02",
    "description": "",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-002",
    "slug": "slug sample 2",
    "author_id": "",
    "content_type": "announcement",
    "excerpt": "",
    "body_markdown": "body-markdown sample 2",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 03",
    "description": "",
    "placeholder": "",
    "status": "scheduled",
    "state_history": [
      {
        "from": null,
        "to": "scheduled",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-003",
    "slug": "slug sample 3",
    "author_id": "",
    "content_type": "release_notes",
    "excerpt": "",
    "body_markdown": "body-markdown sample 3",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 04",
    "description": "",
    "placeholder": "",
    "status": "published",
    "state_history": [
      {
        "from": null,
        "to": "published",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-004",
    "slug": "slug sample 4",
    "author_id": "",
    "content_type": "how_to",
    "excerpt": "",
    "body_markdown": "body-markdown sample 4",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 05",
    "description": "",
    "placeholder": "",
    "status": "archived",
    "state_history": [
      {
        "from": null,
        "to": "archived",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-005",
    "slug": "slug sample 5",
    "author_id": "",
    "content_type": "knowledge_base",
    "excerpt": "",
    "body_markdown": "body-markdown sample 5",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 06",
    "description": "",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-006",
    "slug": "slug sample 6",
    "author_id": "",
    "content_type": "announcement",
    "excerpt": "",
    "body_markdown": "body-markdown sample 6",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 07",
    "description": "",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-007",
    "slug": "slug sample 7",
    "author_id": "",
    "content_type": "release_notes",
    "excerpt": "",
    "body_markdown": "body-markdown sample 7",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 08",
    "description": "",
    "placeholder": "",
    "status": "scheduled",
    "state_history": [
      {
        "from": null,
        "to": "scheduled",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-008",
    "slug": "slug sample 8",
    "author_id": "",
    "content_type": "how_to",
    "excerpt": "",
    "body_markdown": "body-markdown sample 8",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 09",
    "description": "",
    "placeholder": "",
    "status": "published",
    "state_history": [
      {
        "from": null,
        "to": "published",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-009",
    "slug": "slug sample 9",
    "author_id": "",
    "content_type": "knowledge_base",
    "excerpt": "",
    "body_markdown": "body-markdown sample 9",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  },
  {
    "label": "Article 10",
    "description": "",
    "placeholder": "",
    "status": "archived",
    "state_history": [
      {
        "from": null,
        "to": "archived",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "article_id": "article-010",
    "slug": "slug sample 10",
    "author_id": "",
    "content_type": "announcement",
    "excerpt": "",
    "body_markdown": "body-markdown sample 10",
    "hero_media_id": "",
    "reading_time_minutes": 0,
    "locale": "",
    "published_at": "2026-01-01T00:00:00.000Z"
  }
];
