import type { PageProps } from './GeneratedUI.js';

export const model: Omit<PageProps, 'actions'> = {
  "addressRoles": [],
  "addresses": [],
  "allowedTransitions": [],
  "billingContactEmail": "consumer@example.test",
  "billingStatus": "good_standing",
  "channelCatalog": [],
  "conversations": [],
  "createdAt": "2026-09-05T12:00:00.000Z",
  "dataResidency": "us",
  "defaultAddressRole": "Consumer default address role",
  "deliveryPolicies": [],
  "description": "Consumer description",
  "domain": "Consumer domain",
  "employeeCount": 0,
  "industry": "Consumer industry",
  "label": "Consumer label",
  "lastEvent": "Consumer last event",
  "lastEventAt": "2026-09-05T12:00:00.000Z",
  "membershipRecords": [],
  "messageStatuses": [],
  "messages": [],
  "organizationId": "consumer-organization-id",
  "ownerId": "consumer-owner-id",
  "ownerType": "Consumer owner type",
  "ownershipRole": "Consumer ownership role",
  "ownershipTransferredAt": "2026-09-05T12:00:00.000Z",
  "permissionCatalog": [],
  "placeholder": "Consumer placeholder",
  "planTier": "free",
  "preferenceDocument": "Consumer preference document",
  "preferenceMetadata": "Consumer preference metadata",
  "preferenceMutations": 0,
  "preferenceNamespaces": [],
  "preferenceVersion": "Consumer preference version",
  "roleCatalog": [],
  "roleHierarchyEdges": [],
  "rolePermissions": {},
  "sessionRoles": [],
  "stateHistory": [],
  "status": "Consumer status",
  "tagCount": 0,
  "tagMetadata": [],
  "tags": [],
  "templateCatalog": [],
  "updatedAt": "2026-09-05T12:00:00.000Z"
};
