import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "plan_code": "plan-code sample 1",
    "plan_name": "Plan 01",
    "billing_interval": "billing-interval sample 1",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 1",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 1",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 1",
    "owner_type": "owner-type sample 1",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-001",
    "product_family": "product-family sample 1",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 2",
    "plan_name": "Plan 02",
    "billing_interval": "billing-interval sample 2",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 2",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 2",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 2",
    "owner_type": "owner-type sample 2",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-002",
    "product_family": "product-family sample 2",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 3",
    "plan_name": "Plan 03",
    "billing_interval": "billing-interval sample 3",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 3",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 3",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 3",
    "owner_type": "owner-type sample 3",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-003",
    "product_family": "product-family sample 3",
    "status": "private_beta",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 4",
    "plan_name": "Plan 04",
    "billing_interval": "billing-interval sample 4",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 4",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 4",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 4",
    "owner_type": "owner-type sample 4",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-004",
    "product_family": "product-family sample 4",
    "status": "legacy",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 5",
    "plan_name": "Plan 05",
    "billing_interval": "billing-interval sample 5",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 5",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 5",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 5",
    "owner_type": "owner-type sample 5",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-005",
    "product_family": "product-family sample 5",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 6",
    "plan_name": "Plan 06",
    "billing_interval": "billing-interval sample 6",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 6",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 6",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 6",
    "owner_type": "owner-type sample 6",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-006",
    "product_family": "product-family sample 6",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 7",
    "plan_name": "Plan 07",
    "billing_interval": "billing-interval sample 7",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 7",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 7",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 7",
    "owner_type": "owner-type sample 7",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-007",
    "product_family": "product-family sample 7",
    "status": "private_beta",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 8",
    "plan_name": "Plan 08",
    "billing_interval": "billing-interval sample 8",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 8",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 8",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 8",
    "owner_type": "owner-type sample 8",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-008",
    "product_family": "product-family sample 8",
    "status": "legacy",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 9",
    "plan_name": "Plan 09",
    "billing_interval": "billing-interval sample 9",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 9",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 9",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 9",
    "owner_type": "owner-type sample 9",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-009",
    "product_family": "product-family sample 9",
    "status": "active",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  },
  {
    "plan_code": "plan-code sample 10",
    "plan_name": "Plan 10",
    "billing_interval": "billing-interval sample 10",
    "interval_count": 0,
    "amount_minor": 0,
    "currency": "usd",
    "trial_period_days": 0,
    "collection_method": "",
    "billing_anchor_day": 0,
    "pricing_model": "",
    "meter_name": "meter-name sample 10",
    "included_quantity": 0,
    "consumed_quantity": 0,
    "unit_label": "unit-label sample 10",
    "period_start": "2026-01-01T00:00:00.000Z",
    "period_end": "2026-02-01T00:00:00.000Z",
    "rollover_strategy": "",
    "overage_rate_minor": 0,
    "projected_overage_minor": 0,
    "samples": [],
    "owner_id": "owner-id sample 10",
    "owner_type": "owner-type sample 10",
    "ownership_role": "",
    "ownership_transferred_at": "2026-01-01T00:00:00.000Z",
    "plan_id": "plan-010",
    "product_family": "product-family sample 10",
    "status": "deprecated",
    "feature_matrix": [],
    "add_on_ids": [],
    "upgrade_targets": [],
    "downgrade_targets": [],
    "notes": ""
  }
];
