import React from 'react';
import { BillingAmountInput, BillingIntervalSelector, Button, CancellationForm, Checkbox, DatePicker, Input, Select, Stack, StatusSelector, Textarea } from '@oods/components-react';
import '@oods/component-styles/css';

export interface GeneratedUIActions {
  /* @oods-domain-action handleCancel sha256:0bcc174cf532d72131208256a9b18cbc8e4a3dd139e0a23e5ad06e72ef67a5bb */
  /* @oods-domain-source sha256:89d149b638db019f4806a0bce69af5d499298c44874f049d28b48ac41f9b0838 */
  handleCancel: () => void;
  /* @oods-domain-action handleChange sha256:8d34e74d5c32a0ac604752249e369630e382e03991b58d88a9199a0add05b4a7 */
  /* @oods-domain-source sha256:7c3ae6feb9000b30f9248b6c15aa7765871a2d01e93cf9825373f138d43582d9 */
  handleChange: () => void;
  /* @oods-domain-action handleSubmit sha256:40dcacd8dc443bb231a9f4e83cdd8390bbf86979dacc3ed885912064ac94f846 */
  /* @oods-domain-source sha256:39f1e2024f9e76dc58ee38b1ae09943135d4d3f956ac63b59852fef68c598a99 */
  handleSubmit: () => void;
}

export interface PageProps {
  actions: GeneratedUIActions;
  /** Materialized list of valid next states from the current status, computed from the
transitionRules parameter. When transitionRules is null (open model), this contains
all states except the current one. Used by StatusSelector to disable invalid options
and by StatusBadge to indicate available paths.
 */
  allowedTransitions?: string[];
  /** Recurring price expressed in minor units (e.g., cents). */
  amount: number;
  /** Structured metadata about the archival action for compliance and audit purposes.

Properties:
  - method: "manual" | "automated" | "policy" — how the archive was triggered
  - compliance_tags: string[] — regulatory labels (e.g., ["GDPR", "SOX", "HIPAA"])
  - retention_policy_id: string — reference to the retention policy that triggered archival
  - original_status: string — the Stateful status before archival
  - related_entity_count: number — count of related entities also archived (cascade)
 */
  archiveMetadata?: Record<string, unknown>;
  /** Human-readable narrative describing why the entity was archived. */
  archiveReason?: string;
  /** Timestamp for when the entity entered the archived state. */
  archivedAt?: string | null;
  /** User ID or system identifier of the actor who archived this entity.
Set to "system" for automated/policy-driven archival. Supports audit trail queries
like "show all entities archived by user X" or "show all auto-archived entities".
 */
  archivedBy?: string;
  /** Recurrence cadence (monthly, yearly, quarterly, etc.). */
  billingInterval?: string;
  /** Whether the subscription will cancel at the natural billing period end. */
  cancelAtPeriodEnd: boolean;
  /** Free-form explanation captured during cancellation workflows. */
  cancellationReason?: string;
  /** Structured reason code chosen from the allowedReasons parameter. */
  cancellationReasonCode?: string;
  /** Timestamp when cancellation was initiated. */
  cancellationRequestedAt?: string;
  /** Timestamp recording when the entity was first created. */
  createdAt: string;
  /** ISO 4217 currency code used for billing. */
  currency: string;
  /** End timestamp of the current billing cycle. */
  currentPeriodEnd: string;
  /** Decimal progress (0-1) through the active billing cycle. */
  currentPeriodProgress?: number;
  /** Start timestamp of the current billing cycle. */
  currentPeriodStart: string;
  /** Billing contact email address. */
  customerEmail?: string;
  /** Customer or account name associated with the subscription. */
  customerName?: string;
  /** Flag indicating whether the entity is currently archived (soft-deleted). */
  isArchived: boolean;
  /** Lifecycle event associated with the most recent timestamp mutation. */
  lastEvent: string;
  /** Timestamp for the lifecycle event captured in last_event. */
  lastEventAt?: string;
  /** Timestamp of the most recent successful payment. */
  lastPaymentAt?: string;
  /** Timestamp when the next payment attempt should occur. */
  nextPaymentDueAt?: string;
  /** Payment instrument category used for collection. */
  paymentMethodType?: 'card' | 'ach' | 'wire' | 'invoice' | 'other';
  /** Outcome of the most recent collection attempt. Distinct from subscription
lifecycle status — a subscription can be "active" with payment_status "retrying".
 */
  paymentStatus?: 'pending' | 'succeeded' | 'failed' | 'retrying' | 'refunded';
  /** Internal plan code or price identifier. */
  planCode?: string;
  /** Billing interval descriptor (monthly, yearly, etc.). */
  planInterval?: string;
  /** Human-readable plan label shown in headers. */
  planName: string;
  /** Prorated credit or charge in minor currency units generated by a mid-cycle
plan change. Positive values are charges; negative values are credits.
Only populated when the supportProration parameter is true.
 */
  prorationAmount?: number;
  /** Unix timestamp (epoch SECONDS) at which proration is calculated. Pinned when an
upcoming-invoice PREVIEW is requested and MUST be passed identically on commit so the
committed charge equals the previewed amount. The preview is read-only and does NOT
mutate the subscription. Stored as an integer (not a datetime) so the value round-trips
byte-identically between preview and commit — an ISO string normalization could shift it
and desync the previewed vs charged amount. Only populated when supportProration is true.
Source: docs.stripe.com/billing/subscriptions/prorations.
 */
  prorationDate?: number;
  /** Metadata about the most recent restoration action.

Properties:
  - restored_by: string — user ID or "system"
  - restored_fields: string[] — when partial restore, which fields were restored
  - restoration_reason: string — why the entity was restored
  - restored_from_snapshot: boolean — whether restored from a point-in-time snapshot
 */
  restorationMetadata?: Record<string, unknown>;
  /** Timestamp for when the entity was most recently restored from an archived state. */
  restoredAt?: string | null;
  /** Chronological log of state transitions. Each entry records the before/after states,
timestamp, and (when governance is enabled) the actor, reason, and transition metadata.
Rendered by StatusTimeline in the detail and timeline views.

Entry structure:
  - from: string (previous state)
  - to: string (new state)
  - timestamp: ISO 8601 datetime
  - actor_id: string (user/system who triggered the transition, optional)
  - reason: string (human-readable justification, required when requireTransitionReason is true)
  - transition_metadata: Record<string, unknown> (arbitrary context, optional)
 */
  stateHistory?: unknown[];
  /** Current lifecycle status of the subscription. */
  status: 'future' | 'trialing' | 'active' | 'paused' | 'pending_cancellation' | 'past_due' | 'unpaid' | 'terminated';
  /** Primary identifier used across billing and lifecycle systems. */
  subscriptionId: string;
  /** Timestamp for the most recent modification, when available. */
  updatedAt?: string;
}

type BillingAmountInputProps = React.ComponentPropsWithoutRef<typeof BillingAmountInput>;
type BillingIntervalSelectorProps = React.ComponentPropsWithoutRef<typeof BillingIntervalSelector>;
type ButtonProps = React.ComponentPropsWithoutRef<typeof Button>;
type CancellationFormProps = React.ComponentPropsWithoutRef<typeof CancellationForm>;
type CheckboxProps = React.ComponentPropsWithoutRef<typeof Checkbox>;
type DatePickerProps = React.ComponentPropsWithoutRef<typeof DatePicker>;
type InputProps = React.ComponentPropsWithoutRef<typeof Input>;
type SelectProps = React.ComponentPropsWithoutRef<typeof Select>;
type StackProps = React.ComponentPropsWithoutRef<typeof Stack>;
type StatusSelectorProps = React.ComponentPropsWithoutRef<typeof StatusSelector>;
type TextareaProps = React.ComponentPropsWithoutRef<typeof Textarea>;

export const GeneratedUI: React.FC<PageProps> = ({ actions, allowedTransitions, amount, archiveMetadata, archiveReason, archivedAt, archivedBy, billingInterval, cancelAtPeriodEnd, cancellationReason, cancellationReasonCode, cancellationRequestedAt, createdAt, currency, currentPeriodEnd, currentPeriodProgress, currentPeriodStart, customerEmail, customerName, isArchived, lastEvent, lastEventAt, lastPaymentAt, nextPaymentDueAt, paymentMethodType, paymentStatus, planCode, planInterval, planName, prorationAmount, prorationDate, restorationMetadata, restoredAt, stateHistory, status, subscriptionId, updatedAt }) => {
  if (!actions || !Object.prototype.hasOwnProperty.call(actions, 'handleCancel') || typeof actions.handleCancel !== 'function') { throw new Error('GeneratedUI requires actions.handleCancel.'); }
  if (!actions || !Object.prototype.hasOwnProperty.call(actions, 'handleChange') || typeof actions.handleChange !== 'function') { throw new Error('GeneratedUI requires actions.handleChange.'); }
  if (!actions || !Object.prototype.hasOwnProperty.call(actions, 'handleSubmit') || typeof actions.handleSubmit !== 'function') { throw new Error('GeneratedUI requires actions.handleSubmit.'); }

  /* @oods-domain-binding handleCancel */ const handleCancel = () => { actions.handleCancel(); };
  /* @oods-domain-binding handleChange */ const handleChange = () => { actions.handleChange(); };
  const [handleChange_amountState, setHandleChange_amountState] = React.useState<string>(String(amount ?? ''));
  /* @oods-local-binding handleChange_amount */ const handleChange_amount = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_amountState(event.currentTarget.value); };
  const [handleChange_billing_intervalState, setHandleChange_billing_intervalState] = React.useState<string>(String(billingInterval ?? ''));
  /* @oods-local-binding handleChange_billing_interval */ const handleChange_billing_interval = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_billing_intervalState(event.currentTarget.value); };
  const [handleChange_cancel_at_period_endState, setHandleChange_cancel_at_period_endState] = React.useState<boolean>(cancelAtPeriodEnd ?? false);
  /* @oods-local-binding handleChange_cancel_at_period_end */ const handleChange_cancel_at_period_end = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_cancel_at_period_endState(event.currentTarget.checked); };
  const [handleChange_cancellation_reasonState, setHandleChange_cancellation_reasonState] = React.useState<string>(String(cancellationReason ?? ''));
  /* @oods-local-binding handleChange_cancellation_reason */ const handleChange_cancellation_reason = (event: React.ChangeEvent<HTMLTextAreaElement>) => { setHandleChange_cancellation_reasonState(event.currentTarget.value); };
  const [handleChange_cancellation_requested_atState, setHandleChange_cancellation_requested_atState] = React.useState<string>(String(cancellationRequestedAt ?? ''));
  /* @oods-local-binding handleChange_cancellation_requested_at */ const handleChange_cancellation_requested_at = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_cancellation_requested_atState(event.currentTarget.value); };
  const [handleChange_currencyState, setHandleChange_currencyState] = React.useState<string>(String(currency ?? ''));
  /* @oods-local-binding handleChange_currency */ const handleChange_currency = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_currencyState(event.currentTarget.value); };
  const [handleChange_customer_emailState, setHandleChange_customer_emailState] = React.useState<string>(String(customerEmail ?? ''));
  /* @oods-local-binding handleChange_customer_email */ const handleChange_customer_email = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_customer_emailState(event.currentTarget.value); };
  const [handleChange_last_eventState, setHandleChange_last_eventState] = React.useState<string>(String(lastEvent ?? ''));
  /* @oods-local-binding handleChange_last_event */ const handleChange_last_event = (event: React.ChangeEvent<HTMLInputElement>) => { setHandleChange_last_eventState(event.currentTarget.value); };
  const [handleChange_payment_method_typeState, setHandleChange_payment_method_typeState] = React.useState<string>(String(paymentMethodType ?? ''));
  /* @oods-local-binding handleChange_payment_method_type */ const handleChange_payment_method_type = (event: React.ChangeEvent<HTMLSelectElement>) => { setHandleChange_payment_method_typeState(event.currentTarget.value); };
  const [handleChange_statusState, setHandleChange_statusState] = React.useState<string>(String(status ?? ''));
  /* @oods-local-binding handleChange_status */ const handleChange_status = (event: React.ChangeEvent<HTMLSelectElement>) => { setHandleChange_statusState(event.currentTarget.value); };
  /* @oods-domain-binding handleSubmit */ const handleSubmit = () => { actions.handleSubmit(); };

  return (
    <>
      <>
        <Stack id="screen-form-11" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-default)', padding: 'var(--ref-space-inset-default)' }}>
              <Stack id="form-title-1" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-default)' }}>
                      <StatusSelector id="ve-title-28" data-oods-component="StatusSelector" label="Current lifecycle status of the subscription." options={[{"label":"Future","value":"future"},{"label":"Trialing","value":"trialing"},{"label":"Active","value":"active"},{"label":"Paused","value":"paused"},{"label":"Pending Cancellation","value":"pending_cancellation"},{"label":"Past Due","value":"past_due"},{"label":"Unpaid","value":"unpaid"},{"label":"Terminated","value":"terminated"}]} value={handleChange_statusState} onChange={handleChange_status} />
                      <CancellationForm id="ve-title-29" data-oods-component="CancellationForm" reason={cancellationReason} reasonCode={cancellationReasonCode} />
                    </Stack>
              <Stack id="form-fields-8" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-default)' }}>
                      <Stack id="form-field-group-2" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Stack id="slot-field-0-3" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-default)' }}>
                                            <BillingIntervalSelector id="ve-field-0-26" data-oods-component="BillingIntervalSelector" interval={billingInterval} />
                                            <BillingAmountInput id="ve-field-0-27" data-oods-component="BillingAmountInput" amount={amount} currency={currency} />
                                          </Stack>
                              </Stack>
                      <Stack id="form-field-group-4" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Checkbox id="slot-field-1-5" data-oods-component="Checkbox" label="Whether the subscription will cancel at the natural billing period end." checked={handleChange_cancel_at_period_endState} onChange={handleChange_cancel_at_period_end} />
                              </Stack>
                      <Stack id="form-field-group-6" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Textarea id="slot-field-2-7" data-oods-component="Textarea" label="Free-form explanation captured during cancellation workflows." value={handleChange_cancellation_reasonState} onChange={handleChange_cancellation_reason} />
                              </Stack>
                      <Stack id="form-field-group-12" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <DatePicker id="slot-field-3-13" data-oods-component="DatePicker" label="Timestamp when cancellation was initiated." value={handleChange_cancellation_requested_atState} onChange={handleChange_cancellation_requested_at} />
                              </Stack>
                      <Stack id="form-field-group-14" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Input id="slot-field-4-15" data-oods-component="Input" label="ISO 4217 currency code used for billing." placeholder="Enter currency" required value={handleChange_currencyState} onChange={handleChange_currency} />
                              </Stack>
                      <Stack id="form-field-group-16" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Select id="slot-field-5-17" data-oods-component="Select" label="Payment instrument category used for collection." options={[{"value":"card","label":"card"},{"value":"ach","label":"ach"},{"value":"wire","label":"wire"},{"value":"invoice","label":"invoice"},{"value":"other","label":"other"}]} placeholder="Enter payment method type" value={handleChange_payment_method_typeState} onChange={handleChange_payment_method_type} />
                              </Stack>
                      <Stack id="form-field-group-18" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Input id="slot-field-6-19" data-oods-component="Input" label="Billing contact email address." placeholder="Enter customer email" type="email" value={handleChange_customer_emailState} onChange={handleChange_customer_email} />
                              </Stack>
                      <Stack id="form-field-group-20" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Input id="slot-field-7-21" data-oods-component="Input" label="Lifecycle event associated with the most recent timestamp mutation." placeholder="Enter last event" required value={handleChange_last_eventState} onChange={handleChange_last_event} />
                              </Stack>
                      <Stack id="form-field-group-22" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Input id="slot-field-8-23" data-oods-component="Input" label="Recurring price expressed in minor units (e.g., cents)." placeholder="Enter amount" required type="number" value={handleChange_amountState} onChange={handleChange_amount} />
                              </Stack>
                      <Stack id="form-field-group-24" data-oods-component="Stack" data-layout="stack" style={{ display: 'flex', flexDirection: 'column', gap: 'var(--ref-space-cluster-tight)' }}>
                                <Input id="slot-field-9-25" data-oods-component="Input" label="Recurrence cadence (monthly, yearly, quarterly, etc.)." placeholder="Enter billing interval" value={handleChange_billing_intervalState} onChange={handleChange_billing_interval} />
                              </Stack>
                    </Stack>
              <Stack id="form-actions-9" data-oods-component="Stack" data-layout="inline" style={{ display: 'flex', flexDirection: 'row', justifyContent: 'flex-end', padding: 'var(--ref-space-inset-default)' }}>
                      <Button id="form-submit-10" data-oods-component="Button" content="Save" type="submit" />
                    </Stack>
            </Stack>
        <div role="group" aria-label="Screen actions" data-oods-screen-actions="screen-form-11">
          <button type="button" data-oods-action="handleCancel" onClick={() => handleCancel()}>Cancel subscription</button>
          <button type="button" data-oods-action="handleChange" onClick={() => handleChange()}>Change</button>
          <button type="button" data-oods-action="handleSubmit" onClick={() => handleSubmit()}>Submit</button>
        </div>
      </>
    </>
  );
};
