import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Northstar Workspace",
    "description": "Northstar Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-001",
    "title": "Northstar Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 1,
    "completed_mission_count": 1,
    "project_id": "project-001"
  },
  {
    "label": "Harbor Workspace",
    "description": "Harbor Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-002",
    "title": "Harbor Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 2,
    "completed_mission_count": 2,
    "project_id": "project-002"
  },
  {
    "label": "Cedar Workspace",
    "description": "Cedar Workspace",
    "placeholder": "",
    "status": "archived",
    "state_history": [
      {
        "from": null,
        "to": "archived",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-003",
    "title": "Cedar Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 3,
    "completed_mission_count": 3,
    "project_id": "project-003"
  },
  {
    "label": "Summit Workspace",
    "description": "Summit Workspace",
    "placeholder": "",
    "status": "reverted",
    "state_history": [
      {
        "from": null,
        "to": "reverted",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-004",
    "title": "Summit Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 4,
    "completed_mission_count": 4,
    "project_id": "project-004"
  },
  {
    "label": "Orchard Workspace",
    "description": "Orchard Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-005",
    "title": "Orchard Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 5,
    "completed_mission_count": 5,
    "project_id": "project-005"
  },
  {
    "label": "Willow Workspace",
    "description": "Willow Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-006",
    "title": "Willow Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 6,
    "completed_mission_count": 6,
    "project_id": "project-006"
  },
  {
    "label": "Atlas Workspace",
    "description": "Atlas Workspace",
    "placeholder": "",
    "status": "archived",
    "state_history": [
      {
        "from": null,
        "to": "archived",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-007",
    "title": "Atlas Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 7,
    "completed_mission_count": 7,
    "project_id": "project-007"
  },
  {
    "label": "Meadow Workspace",
    "description": "Meadow Workspace",
    "placeholder": "",
    "status": "reverted",
    "state_history": [
      {
        "from": null,
        "to": "reverted",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-008",
    "title": "Meadow Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 8,
    "completed_mission_count": 8,
    "project_id": "project-008"
  },
  {
    "label": "Juniper Workspace",
    "description": "Juniper Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-009",
    "title": "Juniper Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 9,
    "completed_mission_count": 9,
    "project_id": "project-009"
  },
  {
    "label": "Brook Workspace",
    "description": "Brook Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "sprint_id": "sprint-010",
    "title": "Brook Workspace",
    "focus": "",
    "start_date": "",
    "end_date": "",
    "mission_count": 10,
    "completed_mission_count": 10,
    "project_id": "project-010"
  }
];
