import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {handle as compose} from '/Users/systemsystems/.codex/worktrees/s195/OODS-Forge/packages/mcp-server/dist/tools/design.compose.js';
import {handle as generate} from '/Users/systemsystems/.codex/worktrees/s195/OODS-Forge/packages/mcp-server/dist/tools/code.generate.js';
const root='/Users/systemsystems/.codex/worktrees/s195/OODS-Forge';
const sha=s=>createHash('sha256').update(s).digest('hex');
const folder=path.join('/tmp/oods-s195-tz-probe',process.env.TZ.replaceAll('/','-'));fs.mkdirSync(folder,{recursive:true});
const composition=await compose({object:'Subscription',context:'detail'});assert.equal(composition.status,'ok');
const request={schema:composition.schema,framework:'react',profile:'build',options:{theme:'hc',brand:'A'}};
const result=await generate(request);assert.equal(result.status,'ok',JSON.stringify(result.errors));
const files=result.artifact.files.filter(file=>file.path.endsWith('.svg'));assert.equal(files.length,1);
const old=JSON.parse(fs.readFileSync(path.join(root,'artifacts/product-reality/sprint-195/m05/hc/boundary/codegen-react.json'),'utf8'));
const previous=old.result.artifact.files.filter(file=>file.path.endsWith('.svg'));assert.equal(previous.length,1);
fs.writeFileSync(path.join(folder,'request.json'),JSON.stringify(request,null,2)+'\n');
fs.writeFileSync(path.join(folder,'result.json'),JSON.stringify(result,null,2)+'\n');
fs.writeFileSync(path.join(folder,'generated.svg'),files[0].contents);
fs.writeFileSync(path.join(folder,'retained-m05.svg'),previous[0].contents);
const report={timezone:process.env.TZ,resolvedTimezone:Intl.DateTimeFormat().resolvedOptions().timeZone,revision:JSON.parse(fs.readFileSync(path.join(root,'packages/mcp-server/dist/build-revision.json'),'utf8')),requestSha256:sha(JSON.stringify(request)),previousRequestSha256:sha(JSON.stringify(old.request)),sourceHandler:'packages/mcp-server/dist/tools/code.generate.js',inputSource:'same design.compose Subscription/detail request as chart-placement-codegen.s195.spec.ts',path:files[0].path,contentHash:files[0].contentHash,svgSha256:sha(files[0].contents),svgBytes:Buffer.byteLength(files[0].contents),retainedSha256:sha(previous[0].contents),retainedBytes:Buffer.byteLength(previous[0].contents),equalsRetained:files[0].contents===previous[0].contents};
fs.writeFileSync(path.join(folder,'receipt.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
