import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import dotenv from 'dotenv';
const output = path.dirname(new URL(import.meta.url).pathname);
const processes = JSON.parse(execFileSync('pm2', ['jlist'], { encoding: 'utf8' }));
const processRecord = processes.find((p) => p.name === 'oods-forge-bridge');
if (!processRecord) throw new Error('Expected served process missing');
const env = processRecord.pm2_env;
const root = path.resolve(env.pm_cwd, '../..');
const hash = (v) => createHash('sha256').update(v).digest('hex');
const fromFile = fs.existsSync(path.join(root, '.env')) ? dotenv.parse(fs.readFileSync(path.join(root, '.env'))) : {};
const selected = Object.fromEntries(['MCP_SCHEMA_STORE_ROOT', 'MCP_SCHEMA_STORE_DIR', 'MCP_BRIDGE_PORT'].filter((key) => env[key] ?? fromFile[key]).map((key) => [key, env[key] ?? fromFile[key]]));
const serverCwd = path.join(root, 'packages/mcp-server');
const storeRoot = selected.MCP_SCHEMA_STORE_ROOT ?? serverCwd;
const storeDir = path.resolve(storeRoot, selected.MCP_SCHEMA_STORE_DIR ?? '.oods/schemas');
const target = path.join(storeDir, 'user-form-showcase.json');
const get = (args) => execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
const port = Number(selected.MCP_BRIDGE_PORT ?? 4466);
const healthResponse = await fetch(`http://127.0.0.1:${port}/health`);
const health = await healthResponse.json();
let listener;
try { listener = execFileSync('lsof', ['-nP', `-iTCP:${port}`, '-sTCP:LISTEN'], { encoding: 'utf8' }).trim(); } catch (error) { listener = { unavailable: error.message }; }
const files = ['packages/mcp-bridge/dist/server.js', 'packages/mcp-server/dist/index.js', 'packages/mcp-server/dist/tools/catalog.list.js', 'artifacts/structured-data/manifest.json'];
let loaded;
const token = env.BRIDGE_TOKEN ?? fromFile.BRIDGE_TOKEN;
const response = await fetch(`http://127.0.0.1:${port}/run`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(token ? { 'X-Bridge-Token': token } : {}) }, body: JSON.stringify({ tool: 'schema', input: { action: 'load', name: 'user-form-showcase' }, role: 'designer' }), signal: AbortSignal.timeout(30000) });
const body = await response.json();
loaded = { httpStatus: response.status, ok: body.ok, name: body.result?.name, version: body.result?.version, schemaSha256: body.result?.schema ? hash(JSON.stringify(body.result.schema)) : null, error: body.ok ? null : body.message ?? body.error };
const record = fs.existsSync(target) ? JSON.parse(fs.readFileSync(target)) : null;
const result = { observedAt: new Date().toISOString(), operation: 'read-only PM2/process/files/health/schema.load observation', process: { name: processRecord.name, pid: processRecord.pid, cwd: env.pm_cwd, script: env.pm_exec_path, uptime: env.pm_uptime, restarts: env.restart_time }, listener, checkoutRoot: root, checkoutHead: get(['rev-parse', 'HEAD']), implementationDiffSha256: hash(execFileSync('git', ['diff', 'HEAD', '--binary', '--', 'packages', 'scripts', 'configs'], { cwd: root, maxBuffer: 64 * 1024 * 1024 })), trackedDirty: get(['diff', '--name-only', 'HEAD']).split('\n').filter(Boolean).length > 0, selectedStoreConfiguration: selected, storePath: storeDir, storeIdentityLimit: 'Path resolved from current PM2 and .env configuration. The read-only load attempt is reported separately; an HTTP failure does not verify active store identity. Generic health does not attest compiled source revision.', userForm: record ? { path: target, name: record.name, version: record.version, fileSha256: hash(fs.readFileSync(target)), schemaSha256: hash(JSON.stringify(record.schema)), loaded } : { path: target, exists: false, loaded }, builtHashes: Object.fromEntries(files.filter((file) => fs.existsSync(path.join(root, file))).map((file) => [file, hash(fs.readFileSync(path.join(root, file)))])), health: { httpStatus: healthResponse.status, body: health }, servedCompiledRevision: 'unproven; checkout HEAD and built hashes are separate observations', sharedMutation: false };
fs.writeFileSync(path.join(output, process.argv[2] ?? 'served-identity.json'), JSON.stringify(result, null, 2) + '\n');
console.log(JSON.stringify({ checkoutHead: result.checkoutHead, trackedDirty: result.trackedDirty, storePath: result.storePath, userForm: result.userForm, healthStatus: health.status }));
