import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Media 01",
    "description": "",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-001",
    "asset_type": "image",
    "mime_type": "mime-type sample 1",
    "storage_bucket": "storage-bucket sample 1",
    "object_key": "object-key sample 1",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 02",
    "description": "",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-002",
    "asset_type": "video",
    "mime_type": "mime-type sample 2",
    "storage_bucket": "storage-bucket sample 2",
    "object_key": "object-key sample 2",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 03",
    "description": "",
    "placeholder": "",
    "status": "available",
    "state_history": [
      {
        "from": null,
        "to": "available",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-003",
    "asset_type": "audio",
    "mime_type": "mime-type sample 3",
    "storage_bucket": "storage-bucket sample 3",
    "object_key": "object-key sample 3",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 04",
    "description": "",
    "placeholder": "",
    "status": "deprecated",
    "state_history": [
      {
        "from": null,
        "to": "deprecated",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-004",
    "asset_type": "document",
    "mime_type": "mime-type sample 4",
    "storage_bucket": "storage-bucket sample 4",
    "object_key": "object-key sample 4",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 05",
    "description": "",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-005",
    "asset_type": "image",
    "mime_type": "mime-type sample 5",
    "storage_bucket": "storage-bucket sample 5",
    "object_key": "object-key sample 5",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 06",
    "description": "",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-006",
    "asset_type": "video",
    "mime_type": "mime-type sample 6",
    "storage_bucket": "storage-bucket sample 6",
    "object_key": "object-key sample 6",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 07",
    "description": "",
    "placeholder": "",
    "status": "available",
    "state_history": [
      {
        "from": null,
        "to": "available",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-007",
    "asset_type": "audio",
    "mime_type": "mime-type sample 7",
    "storage_bucket": "storage-bucket sample 7",
    "object_key": "object-key sample 7",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 08",
    "description": "",
    "placeholder": "",
    "status": "deprecated",
    "state_history": [
      {
        "from": null,
        "to": "deprecated",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-008",
    "asset_type": "document",
    "mime_type": "mime-type sample 8",
    "storage_bucket": "storage-bucket sample 8",
    "object_key": "object-key sample 8",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 09",
    "description": "",
    "placeholder": "",
    "status": "ingested",
    "state_history": [
      {
        "from": null,
        "to": "ingested",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-009",
    "asset_type": "image",
    "mime_type": "mime-type sample 9",
    "storage_bucket": "storage-bucket sample 9",
    "object_key": "object-key sample 9",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  },
  {
    "label": "Media 10",
    "description": "",
    "placeholder": "",
    "status": "processing",
    "state_history": [
      {
        "from": null,
        "to": "processing",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "ingested",
        "title": "Ingested",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "ingested",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "media_id": "media-010",
    "asset_type": "video",
    "mime_type": "mime-type sample 10",
    "storage_bucket": "storage-bucket sample 10",
    "object_key": "object-key sample 10",
    "source_url": "",
    "checksum": "",
    "file_size_bytes": 0,
    "width_px": 0,
    "height_px": 0,
    "duration_seconds": 0,
    "transcoding_profiles": []
  }
];
