import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Northstar Workspace",
    "description": "Northstar Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-001",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-001",
    "title": "Northstar Workspace",
    "session_type": "review",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-001",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-001"
  },
  {
    "label": "Harbor Workspace",
    "description": "Harbor Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-002",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-002",
    "title": "Harbor Workspace",
    "session_type": "planning",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-002",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-002"
  },
  {
    "label": "Cedar Workspace",
    "description": "Cedar Workspace",
    "placeholder": "",
    "status": "abandoned",
    "state_history": [
      {
        "from": null,
        "to": "abandoned",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-003",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-003",
    "title": "Cedar Workspace",
    "session_type": "custom",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-003",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-003"
  },
  {
    "label": "Summit Workspace",
    "description": "Summit Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-004",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-004",
    "title": "Summit Workspace",
    "session_type": "check-in",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-004",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-004"
  },
  {
    "label": "Orchard Workspace",
    "description": "Orchard Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-005",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-005",
    "title": "Orchard Workspace",
    "session_type": "research",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-005",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-005"
  },
  {
    "label": "Willow Workspace",
    "description": "Willow Workspace",
    "placeholder": "",
    "status": "abandoned",
    "state_history": [
      {
        "from": null,
        "to": "abandoned",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-006",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-006",
    "title": "Willow Workspace",
    "session_type": "review",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-006",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-006"
  },
  {
    "label": "Atlas Workspace",
    "description": "Atlas Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-007",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-007",
    "title": "Atlas Workspace",
    "session_type": "planning",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-007",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-007"
  },
  {
    "label": "Meadow Workspace",
    "description": "Meadow Workspace",
    "placeholder": "",
    "status": "completed",
    "state_history": [
      {
        "from": null,
        "to": "completed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-008",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-008",
    "title": "Meadow Workspace",
    "session_type": "custom",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-008",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-008"
  },
  {
    "label": "Juniper Workspace",
    "description": "Juniper Workspace",
    "placeholder": "",
    "status": "abandoned",
    "state_history": [
      {
        "from": null,
        "to": "abandoned",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-009",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-009",
    "title": "Juniper Workspace",
    "session_type": "check-in",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-009",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-009"
  },
  {
    "label": "Brook Workspace",
    "description": "Brook Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "started",
        "title": "Started",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "started",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-010",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "session_id": "session-010",
    "title": "Brook Workspace",
    "session_type": "research",
    "agent": "Agent",
    "summary": "",
    "sprint_id": "sprint-010",
    "started_at": "2026-09-01T12:00:00.000Z",
    "completed_at": "2026-09-01T12:00:00.000Z",
    "captures": [],
    "next_steps": [],
    "project_id": "project-010"
  }
];
