import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Northstar Workspace",
    "description": "Northstar Workspace",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "USD",
    "pricing_model": "one_time",
    "billing_interval": "one_time",
    "tax_behavior": "exclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-001",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-001",
    "sku": "Sku",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Harbor Workspace",
    "description": "Harbor Workspace",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "EUR",
    "pricing_model": "subscription",
    "billing_interval": "month",
    "tax_behavior": "inclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-002",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-002",
    "sku": "Sku",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Cedar Workspace",
    "description": "Cedar Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "GBP",
    "pricing_model": "usage_based",
    "billing_interval": "year",
    "tax_behavior": "exclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-003",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-003",
    "sku": "Sku",
    "inventory_status": "backorder",
    "release_channel": "limited",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Summit Workspace",
    "description": "Summit Workspace",
    "placeholder": "",
    "status": "retired",
    "state_history": [
      {
        "from": null,
        "to": "retired",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "AUD",
    "pricing_model": "one_time",
    "billing_interval": "one_time",
    "tax_behavior": "inclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-004",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-004",
    "sku": "Sku",
    "inventory_status": "discontinued",
    "release_channel": "general_availability",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Orchard Workspace",
    "description": "Orchard Workspace",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "USD",
    "pricing_model": "subscription",
    "billing_interval": "month",
    "tax_behavior": "exclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-005",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-005",
    "sku": "Sku",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Willow Workspace",
    "description": "Willow Workspace",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "EUR",
    "pricing_model": "usage_based",
    "billing_interval": "year",
    "tax_behavior": "inclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-006",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-006",
    "sku": "Sku",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Atlas Workspace",
    "description": "Atlas Workspace",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "GBP",
    "pricing_model": "one_time",
    "billing_interval": "one_time",
    "tax_behavior": "exclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-007",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-007",
    "sku": "Sku",
    "inventory_status": "backorder",
    "release_channel": "limited",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Meadow Workspace",
    "description": "Meadow Workspace",
    "placeholder": "",
    "status": "retired",
    "state_history": [
      {
        "from": null,
        "to": "retired",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "AUD",
    "pricing_model": "subscription",
    "billing_interval": "month",
    "tax_behavior": "inclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-008",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-008",
    "sku": "Sku",
    "inventory_status": "discontinued",
    "release_channel": "general_availability",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Juniper Workspace",
    "description": "Juniper Workspace",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "USD",
    "pricing_model": "usage_based",
    "billing_interval": "year",
    "tax_behavior": "exclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-009",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-009",
    "sku": "Sku",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Brook Workspace",
    "description": "Brook Workspace",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "EUR",
    "pricing_model": "one_time",
    "billing_interval": "one_time",
    "tax_behavior": "inclusive",
    "classification_metadata": {},
    "categories": [],
    "primary_category_id": "primary-category-010",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-010",
    "sku": "Sku",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  }
];
