export const model = {
  "addressRoles": [],
  "addresses": [],
  "allowedTransitions": [],
  "channelCatalog": [],
  "conversations": [],
  "createdAt": "2026-09-05T12:00:00.000Z",
  "defaultAddressRole": "Consumer default address role",
  "deliveryPolicies": [],
  "description": "Consumer description",
  "lastEvent": "Consumer last event",
  "lastEventAt": "2026-09-05T12:00:00.000Z",
  "membershipRecords": [],
  "messageStatuses": [],
  "messages": [],
  "name": "Consumer name",
  "permissionCatalog": [],
  "preferenceDocument": "Consumer preference document",
  "preferenceMetadata": "Consumer preference metadata",
  "preferenceMutations": 0,
  "preferenceNamespaces": [],
  "preferenceVersion": "Consumer preference version",
  "preferredName": "Consumer preferred name",
  "primaryEmail": "consumer@example.test",
  "role": "end_user",
  "roleCatalog": [],
  "roleHierarchyEdges": [],
  "rolePermissions": {},
  "sessionRoles": [],
  "stateHistory": [],
  "status": "Consumer status",
  "tagCount": 0,
  "tagMetadata": [],
  "tags": [],
  "templateCatalog": [],
  "timezone": "Consumer timezone",
  "updatedAt": "2026-09-05T12:00:00.000Z",
  "userId": "consumer-user-id"
};
