import json,pathlib
r=pathlib.Path(__file__).resolve().parent
report=json.loads((r/'verification.json').read_text());rows=[]
for o in report['objects']:
 for f in report['frameworks']:
  before=json.loads((r/'before'/o/f/'craft.json').read_text())['views'];after=json.loads((r/'after'/o/f/'craft.json').read_text())['views']
  for a in after:
   b=next(b for b in before if (b['context'],b['width'])==(a['context'],a['width']))
   rows.append({'object':o,'framework':f,'context':a['context'],'width':str(a['width']),'before':'before/'+b['output']+'/'+b['screenshot'],'after':'after/'+a['output']+'/'+a['screenshot']})
html='''<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>S198 M04 — forms and sample data</title>
<style>body{font:16px system-ui;background:#14181d;color:#ebedef;margin:32px auto;max-width:1400px;padding:0 24px}h1{font-size:28px}p{line-height:1.5;color:#bdc5cd}nav{display:flex;gap:12px;flex-wrap:wrap;margin:24px 0}select{padding:8px;background:#242c35;color:inherit;border:1px solid #606870;border-radius:5px}.pair{display:grid;grid-template-columns:1fr 1fr;gap:20px}.shot{background:#20262d;border:1px solid #49525d;padding:12px;max-height:900px;overflow:auto}img{display:block;width:100%;height:auto}a{color:#8dc7fc}small{display:block;color:#aeb8c3;margin-bottom:12px}@media(max-width:700px){.pair{grid-template-columns:1fr}}</style>
<h1>Forms and sample data — Sprint 198 M04</h1><p>60 main views + 6 seeded-cancellation views · React and Vue · 390 / 820 / 1440 · brand A / light. Every accepted view has zero browser errors, viewport overflow or cross-framework text/value differences. Required marks stay inline. Built for review; builderSelfCertified: false.</p>
<p>Before: 9739f122d. After: HEAD. Labels and help, native inputs, catalog names and options, a single Save, and one deterministic seed policy. The 18 seed tables identify every field value and its rule. Historical diagnostic captures are retained separately and excluded from acceptance.</p>
<p><a href="verification.json">Verification and artifact attribution</a> · <a href="README.md">Item mapping and limits</a> · <a href="subscription-pixels.json">Subscription pixel attribution</a> · <a href="item-mapping.json">Exact receipt lines</a> · <a href="seeds/Organization/seed-table.json">Organization seeds</a> · <a href="seeds/User/seed-table.json">User seeds</a></p>
<p>Pending cancellation, with the same reason code, filled datetime and checked checkbox: <a href="after/Subscription/seeded-cancellation/react/390.png">React 390</a> · <a href="after/Subscription/seeded-cancellation/vue/390.png">Vue 390</a> · <a href="after/Subscription/seeded-cancellation/react/proof.json">React proof</a> · <a href="after/Subscription/seeded-cancellation/vue/proof.json">Vue proof</a>.</p>
<nav id="controls"></nav><section class="pair"><article><h2>Before</h2><small id="before-label"></small><div class="shot"><a id="before-link"><img id="before-img"></a></div></article><article><h2>After</h2><small id="after-label"></small><div class="shot"><a id="after-link"><img id="after-img"></a></div></article></section>
<script>const rows=ROWS;const selected={object:'Organization',framework:'react',context:'form',width:'390'};for(const key of Object.keys(selected)){const label=document.createElement('label');label.textContent=key+' ';const select=document.createElement('select');for(const value of [...new Set(rows.map(row=>row[key]))]){const option=document.createElement('option');option.value=value;option.textContent=value;option.selected=value===selected[key];select.append(option)}label.append(select);document.getElementById('controls').append(label);select.onchange=()=>{selected[key]=select.value;update()}}function update(){const row=rows.find(row=>Object.keys(selected).every(key=>row[key]===selected[key]));for(const phase of ['before','after']){const src=row[phase];document.getElementById(phase+'-img').src=src;document.getElementById(phase+'-img').alt=src;document.getElementById(phase+'-link').href=src;document.getElementById(phase+'-label').textContent=src}}update();</script>'''
(r/'index.html').write_text(html.replace('ROWS',json.dumps(rows)).replace('After: HEAD','After: '+report['sourceHead'][:9]))
