export const model = {
  "allowedTransitions": [],
  "amount": 0,
  "archiveMetadata": {},
  "archiveReason": "Consumer archive reason",
  "archivedAt": "Consumer archived at",
  "archivedBy": "Consumer archived by",
  "billingInterval": "Consumer billing interval",
  "cancelAtPeriodEnd": false,
  "cancellationReason": "Consumer cancellation reason",
  "cancellationReasonCode": "Consumer cancellation reason code",
  "cancellationRequestedAt": "2026-09-05T12:00:00.000Z",
  "createdAt": "2026-09-05T12:00:00.000Z",
  "currency": "Consumer currency",
  "currentPeriodEnd": "2026-09-05T12:00:00.000Z",
  "currentPeriodProgress": 0,
  "currentPeriodStart": "2026-09-05T12:00:00.000Z",
  "customerEmail": "consumer@example.test",
  "customerName": "Consumer customer name",
  "isArchived": false,
  "lastEvent": "Consumer last event",
  "lastEventAt": "2026-09-05T12:00:00.000Z",
  "lastPaymentAt": "2026-09-05T12:00:00.000Z",
  "nextPaymentDueAt": "2026-09-05T12:00:00.000Z",
  "paymentMethodType": "card",
  "paymentStatus": "pending",
  "planCode": "Consumer plan code",
  "planInterval": "Consumer plan interval",
  "planName": "Consumer plan name",
  "prorationAmount": 0,
  "prorationDate": 0,
  "restorationMetadata": {},
  "restoredAt": "Consumer restored at",
  "stateHistory": [],
  "status": "future",
  "subscriptionId": "consumer-subscription-id",
  "updatedAt": "2026-09-05T12:00:00.000Z"
};
