import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "label": "Product 01",
    "description": "",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 1",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-001",
    "sku": "sku sample 1",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Product 02",
    "description": "",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 2",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-002",
    "sku": "sku sample 2",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Product 03",
    "description": "",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 3",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-003",
    "sku": "sku sample 3",
    "inventory_status": "backorder",
    "release_channel": "limited",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Product 04",
    "description": "",
    "placeholder": "",
    "status": "retired",
    "state_history": [
      {
        "from": null,
        "to": "retired",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 4",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-004",
    "sku": "sku sample 4",
    "inventory_status": "discontinued",
    "release_channel": "general_availability",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Product 05",
    "description": "",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 5",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-005",
    "sku": "sku sample 5",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Product 06",
    "description": "",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 6",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-006",
    "sku": "sku sample 6",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Product 07",
    "description": "",
    "placeholder": "",
    "status": "active",
    "state_history": [
      {
        "from": null,
        "to": "active",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 7",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-007",
    "sku": "sku sample 7",
    "inventory_status": "backorder",
    "release_channel": "limited",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  },
  {
    "label": "Product 08",
    "description": "",
    "placeholder": "",
    "status": "retired",
    "state_history": [
      {
        "from": null,
        "to": "retired",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 8",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-008",
    "sku": "sku sample 8",
    "inventory_status": "discontinued",
    "release_channel": "general_availability",
    "requires_subscription": false,
    "support_level": "premium",
    "summary_blurb": ""
  },
  {
    "label": "Product 09",
    "description": "",
    "placeholder": "",
    "status": "draft",
    "state_history": [
      {
        "from": null,
        "to": "draft",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 9",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-009",
    "sku": "sku sample 9",
    "inventory_status": "in_stock",
    "release_channel": "alpha",
    "requires_subscription": false,
    "support_level": "enterprise",
    "summary_blurb": ""
  },
  {
    "label": "Product 10",
    "description": "",
    "placeholder": "",
    "status": "in_review",
    "state_history": [
      {
        "from": null,
        "to": "in_review",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "created",
        "title": "Created",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "created",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 10",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "classification_metadata": "",
    "categories": [],
    "primary_category_id": "",
    "primary_category_path": "",
    "tags": [],
    "tag_count": 0,
    "tag_preview": "",
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 0,
    "pageSize": 0,
    "totalItems": 0,
    "totalPages": 0,
    "product_id": "product-010",
    "sku": "sku sample 10",
    "inventory_status": "low_stock",
    "release_channel": "beta",
    "requires_subscription": false,
    "support_level": "standard",
    "summary_blurb": ""
  }
];
