import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { handle as compose } from '../../../../packages/mcp-server/src/tools/design.compose.js';
import { handle as generate } from '../../../../packages/mcp-server/src/tools/code.generate.js';
const output = path.resolve('artifacts/product-reality/sprint-199/m01');
const rows = [];
for (const object of ['Organization', 'User', 'Evidence', 'Mission']) {
  const directory = path.join(output, 'apps', object.toLowerCase());
  const before = JSON.parse(fs.readFileSync(path.join(directory, 'composition.json'), 'utf8'));
  const after = await compose({ object, context: 'workflow' });
  assert.deepEqual(JSON.parse(JSON.stringify(after.schema)), before.schema, `${object}: composed schema changed after browser capture`);
  for (const framework of ['react', 'vue'] as const) {
    const original = JSON.parse(fs.readFileSync(path.join(directory, `${framework}-generation.json`), 'utf8'));
    const regenerated = await generate({ schema: after.schema, framework, profile: 'build' });
    assert.equal(regenerated.status, 'ok');
    assert.deepEqual(JSON.parse(JSON.stringify(regenerated.artifact)), original.artifact, `${object}/${framework}: generated bytes changed after browser capture`);
    rows.push({ object, framework, artifactHash: regenerated.artifact!.contentHash, equal: true });
  }
}
const sourceManifest = JSON.parse(fs.readFileSync(path.join(output, 'source-manifest.json'), 'utf8'));
const finalSources = sourceManifest.files.map((row: { path: string }) => ({ path: row.path, sha256: createHash('sha256').update(fs.readFileSync(row.path)).digest('hex') }));
fs.writeFileSync(path.join(output, 'post-capture-equivalence.json'), JSON.stringify({ reason: 'The final filter fallback also excludes a constant status enum; all four captured current-object schemas and eight complete generated artifacts remain identical.', rows, finalSources, builderSelfCertified: false }, null, 2) + '\n');
