import type { SharedScenario } from './types.js';

export const sharedScenarios: readonly SharedScenario[] = [
  { id: 'badge-status', oodsComponentId: 'Badge', props: { content: 'Past due', tone: 'critical', emphasis: 'solid' }, slots: {}, initialState: { tone: 'critical' }, event: { name: 'render', trigger: 'mount', expected: 'visible status text and decorative icon treatment' }, assertions: ['content is visible', 'badge is noninteractive'] },
  { id: 'banner-dismissible', oodsComponentId: 'Banner', props: { title: 'Payment failed', detail: 'Update the card', tone: 'critical', dismissLabel: 'Dismiss payment warning' }, slots: { actions: ['Update card'] }, initialState: { dismissed: false }, event: { name: 'dismiss', trigger: 'activate dismiss button', expected: 'dismiss event emitted once' }, assertions: ['critical banner has alert role', 'dismiss button is named'] },
  { id: 'button-activate', oodsComponentId: 'Button', props: { content: 'Save changes', intent: 'neutral', size: 'md' }, slots: { default: 'Save changes' }, initialState: { disabled: false }, event: { name: 'activate', trigger: 'pointer click or Enter', expected: 'activation handler called once' }, assertions: ['native type defaults to button', 'focus is visible'] },
  { id: 'card-elevated-content', oodsComponentId: 'Card', props: { elevated: true }, slots: { default: 'Account summary' }, initialState: { elevated: true }, event: { name: 'render', trigger: 'mount', expected: 'semantic container with visible content' }, assertions: ['content is not empty', 'elevated state is exposed'] },
  { id: 'card-header-supporting-text', oodsComponentId: 'CardHeader', props: { title: 'Account summary', supportingText: 'Current subscription' }, slots: {}, initialState: { heading: 'h3' }, event: { name: 'render', trigger: 'mount', expected: 'h3 heading and visible supporting text' }, assertions: ['title is a real h3 heading', 'supporting text is visible'] },
  { id: 'checkbox-controlled', oodsComponentId: 'Checkbox', props: { id: 'marketing', label: 'Product updates', checked: false, required: true, help: 'Choose whether to subscribe' }, slots: {}, initialState: { checked: false }, event: { name: 'change', trigger: 'click checkbox', expected: 'checked=true emitted once' }, assertions: ['label targets input', 'help describes input'] },
  { id: 'color-swatch-label-and-chip', oodsComponentId: 'ColorSwatch', props: { color: '#2563eb', label: 'Ocean blue' }, slots: {}, initialState: { color: '#2563eb' }, event: { name: 'render', trigger: 'mount in normal and forced-colors modes', expected: 'decorative chip with an always-visible Ocean blue label' }, assertions: ['data-swatch-color exposes the resolved color', 'chip is decorative', 'text label remains visible without color'] },
  { id: 'colorized-badge-color-marker', oodsComponentId: 'ColorizedBadge', props: { label: 'Approved', status: 'active', color: '#15803d', tone: 'success', emphasis: 'subtle' }, slots: {}, initialState: { variant: 'colorized' }, event: { name: 'render', trigger: 'mount in normal and forced-colors modes', expected: 'noninteractive status label with a decorative color marker' }, assertions: ['Approved label remains visible without color', 'data-badge-color exposes the resolved color', 'default variant is colorized', 'badge is noninteractive'] },
  { id: 'date-picker-bounded', oodsComponentId: 'DatePicker', props: { id: 'renewal', label: 'Renewal date', value: '2026-09-30', min: '2026-09-01', max: '2026-12-31', step: 1 }, slots: {}, initialState: { value: '2026-09-30' }, event: { name: 'change', trigger: 'enter 2026-10-01', expected: 'ISO value emitted' }, assertions: ['native input type is date', 'label targets input'] },
  { id: 'detail-header-heading-level', oodsComponentId: 'DetailHeader', props: { title: 'Subscription details', subtitle: 'Pro plan', metadata: 'Renews monthly', as: 'h1', level: 2 }, slots: {}, initialState: { heading: 'h1' }, event: { name: 'render', trigger: 'mount with as=h1 and level=2', expected: 'as selects h1 with visible subtitle and metadata' }, assertions: ['title is a real h1 heading', 'as takes precedence over level', 'subtitle and metadata are visible'] },
  { id: 'grid-responsive', oodsComponentId: 'Grid', props: { minColumnWidth: '16rem', gap: 'md', align: 'stretch' }, slots: { default: ['First card', 'Second card'] }, initialState: { columns: 'auto-fit' }, event: { name: 'render', trigger: 'resize across phone and desktop widths', expected: 'content reflows without clipping' }, assertions: ['two children remain visible', 'DOM order is preserved'] },
  { id: 'input-invalid', oodsComponentId: 'Input', props: { id: 'email', label: 'Email', type: 'email', value: 'invalid', required: true, help: 'Use a work address', validation: { state: 'error', message: 'Enter a valid email' } }, slots: {}, initialState: { value: 'invalid' }, event: { name: 'input', trigger: 'replace value with user@example.com', expected: 'new value emitted' }, assertions: ['label targets input', 'error is associated', 'aria-invalid is true'] },
  { id: 'select-controlled', oodsComponentId: 'Select', props: { id: 'plan', label: 'Plan', value: 'pro', options: [{ value: 'basic', label: 'Basic' }, { value: 'pro', label: 'Pro' }] }, slots: {}, initialState: { value: 'pro' }, event: { name: 'change', trigger: 'choose Basic', expected: 'basic emitted once' }, assertions: ['label targets select', 'selected option is visible'] },
  { id: 'stack-wrapped-row', oodsComponentId: 'Stack', props: { direction: 'row', gap: 'sm', align: 'center', wrap: true }, slots: { default: ['Primary', 'Secondary'] }, initialState: { direction: 'row', wrap: true }, event: { name: 'render', trigger: 'resize to phone width', expected: 'children wrap in DOM order' }, assertions: ['two children remain visible', 'gap token is used'] },
  { id: 'table-selectable-row', oodsComponentId: 'Table', props: { caption: 'Subscriptions', columns: [{ key: 'name', label: 'Name' }, { key: 'status', label: 'Status' }], rows: [{ id: 'sub-1', name: 'Acme', status: 'Active' }], density: 'compact', selectable: true }, slots: {}, initialState: { activeRowId: null }, event: { name: 'rowActivate', trigger: 'press Enter on Acme row action', expected: 'sub-1 emitted once' }, assertions: ['caption names table', 'header cells and data cells are semantic'] },
  { id: 'tabs-keyboard', oodsComponentId: 'Tabs', props: { ariaLabel: 'Account sections', defaultSelectedId: 'overview', items: [{ id: 'overview', label: 'Overview', panel: 'Summary' }, { id: 'billing', label: 'Billing', panel: 'Invoices' }] }, slots: {}, initialState: { selectedId: 'overview' }, event: { name: 'change', trigger: 'ArrowRight from Overview', expected: 'billing selected and focused' }, assertions: ['tablist is named', 'selected panel is visible', 'inactive panel is hidden'] },
  { id: 'text-semantic', oodsComponentId: 'Text', props: { content: 'Account owner', as: 'strong', size: 'md', weight: 'semibold' }, slots: { default: 'Account owner' }, initialState: { element: 'strong' }, event: { name: 'render', trigger: 'mount', expected: 'safe intrinsic element with visible text' }, assertions: ['content is not empty', 'strong element is emitted'] },
  { id: 'textarea-controlled', oodsComponentId: 'Textarea', props: { id: 'notes', label: 'Notes', value: 'Call before renewal', rows: 4, help: 'Visible to account managers' }, slots: {}, initialState: { value: 'Call before renewal' }, event: { name: 'input', trigger: 'append a sentence', expected: 'updated text emitted' }, assertions: ['label targets textarea', 'help describes textarea'] },
  { id: 'viz-area-preview-frame-placeholder-and-slot', oodsComponentId: 'VizAreaPreview', props: { width: 640, height: 360 }, slots: { default: 'Authored area preview content' }, initialState: { hasContent: true }, event: { name: 'render', trigger: 'remove the default slot and then restore it', expected: 'empty frame shows Area preview (640 x 360); authored content replaces the placeholder' }, assertions: ['data-viz-preview-type is area', 'dimensions are exposed on the frame', 'placeholder appears only without authored content', 'renders no chart pixels', 'not visualization evidence'] },
];
