import type { PageProps } from './GeneratedUI.js';

export const model: Omit<PageProps, 'actions'> = {
  "addOnIds": [],
  "amountMinor": 0,
  "billingAnchorDay": 0,
  "billingInterval": "month",
  "collectionMethod": "Consumer collection method",
  "consumedQuantity": 0,
  "currency": "USD",
  "downgradeTargets": [],
  "featureMatrix": [],
  "includedQuantity": 0,
  "intervalCount": 0,
  "meterName": "Consumer meter name",
  "notes": "Consumer notes",
  "overageRateMinor": 0,
  "ownerId": "consumer-owner-id",
  "ownerType": "Consumer owner type",
  "ownershipRole": "Consumer ownership role",
  "ownershipTransferredAt": "2026-09-05T12:00:00.000Z",
  "periodEnd": "2026-09-05",
  "periodStart": "2026-09-05",
  "planCode": "enterprise-monthly",
  "planId": "consumer-plan-id",
  "planName": "Enterprise",
  "pricingModel": "Consumer pricing model",
  "productFamily": "Consumer product family",
  "projectedOverageMinor": 0,
  "rolloverStrategy": "Consumer rollover strategy",
  "samples": [],
  "status": "active",
  "trialPeriodDays": 0,
  "unitLabel": "Consumer unit label",
  "upgradeTargets": []
};
