import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "status": "pending",
    "state_history": [
      {
        "from": null,
        "to": "pending",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 1",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-001",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "card",
    "channel": "online",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "authorized",
    "state_history": [
      {
        "from": null,
        "to": "authorized",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 2",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-002",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "bank_transfer",
    "channel": "in_app",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "settled",
    "state_history": [
      {
        "from": null,
        "to": "settled",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 3",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-003",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "digital_wallet",
    "channel": "point_of_sale",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "failed",
    "state_history": [
      {
        "from": null,
        "to": "failed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 4",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-004",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "invoice",
    "channel": "partner",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "refunded",
    "state_history": [
      {
        "from": null,
        "to": "refunded",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 5",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-005",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "card",
    "channel": "online",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "pending",
    "state_history": [
      {
        "from": null,
        "to": "pending",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 6",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-006",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "bank_transfer",
    "channel": "in_app",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "authorized",
    "state_history": [
      {
        "from": null,
        "to": "authorized",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 7",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-007",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "digital_wallet",
    "channel": "point_of_sale",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "settled",
    "state_history": [
      {
        "from": null,
        "to": "settled",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 8",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-008",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "invoice",
    "channel": "partner",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "failed",
    "state_history": [
      {
        "from": null,
        "to": "failed",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 9",
    "billing_interval": "",
    "tax_behavior": "exclusive",
    "cancel_at_period_end": false,
    "is_archived": false,
    "archived_at": null,
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-009",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "card",
    "channel": "online",
    "payment_reference": "",
    "risk_score": 0
  },
  {
    "status": "refunded",
    "state_history": [
      {
        "from": null,
        "to": "refunded",
        "at": "2026-09-01T12:00:00.000Z",
        "event": "initiated",
        "title": "Initiated",
        "reason": "Sample record created"
      }
    ],
    "allowed_transitions": [],
    "created_at": "2026-09-01T12:00:00.000Z",
    "updated_at": "2026-09-01T12:00:00.000Z",
    "last_event": "initiated",
    "last_event_at": "2026-09-01T12:00:00.000Z",
    "unit_amount_cents": 0,
    "currency": "usd",
    "pricing_model": "pricing-model sample 10",
    "billing_interval": "",
    "tax_behavior": "inclusive",
    "cancel_at_period_end": false,
    "is_archived": true,
    "archived_at": "2026-09-07T12:00:00.000Z",
    "restored_at": "2026-01-01T00:00:00.000Z",
    "archive_reason": "",
    "archived_by": "",
    "archive_metadata": {},
    "restoration_metadata": {},
    "transaction_id": "transaction-010",
    "user_id": "",
    "organization_id": "",
    "occurred_at": "2026-01-01T00:00:00.000Z",
    "payment_method": "bank_transfer",
    "channel": "in_app",
    "payment_reference": "",
    "risk_score": 0
  }
];
