import { analyzeVizSpec, generateNarrativeSummary } from '/Users/systemsystems/portfolio/Design-Tools/OODS-Forge/packages/viz-core/dist/index.js';
const facetLayout = { trait:'LayoutFacet', columns:{field:'panel',trait:'FacetField'} };
const shapeRows = () => { const rows=[]; for(const panel of ['P']){ rows.push({x:1,y:20,panel,shp:'a'});rows.push({x:2,y:16,panel,shp:'a'});rows.push({x:3,y:12,panel,shp:'a'}); rows.push({x:3,y:40,panel,shp:'b'});rows.push({x:4,y:36,panel,shp:'b'});rows.push({x:5,y:32,panel,shp:'b'}); } return rows; };
const enc = { x:{field:'x',trait:'EncodingX',type:'quantitative'}, y:{field:'y',trait:'EncodingY',type:'quantitative',aggregate:'average'}, shape:{field:'shp',trait:'EncodingShape'} };
const spec = { $schema:'x', id:'t', name:'t', data:{name:'d',values:shapeRows()}, marks:[{trait:'MarkPoint',encodings:enc},{trait:'MarkLine',encodings:enc}], encoding:enc, a11y:{} };
const a = analyzeVizSpec(spec);
console.log('analyzeVizSpec keys:', Object.keys(a));
console.log('correlation=', a.correlation);
const nar = generateNarrativeSummary(spec);
console.log('narrative keys:', Object.keys(nar));
console.log(JSON.stringify(nar, null, 1).slice(0, 1500));
