import { afterEach, describe, expect, it } from 'vitest';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { buildGeneratedArtifact } from '../../packages/mcp-server/src/codegen/artifact-envelope.js';
import { consumerEntries } from '../../scripts/design-loop/serve.js';
import { compareReceipts, diff } from '../../scripts/design-loop/diff.js';
import { outputDirectory, relativeFile, validateReceipt, type CaptureRequest } from '../../scripts/design-loop/common.js';
import { render } from '../../scripts/design-loop/render.js';
import { status } from '../../scripts/design-loop/status.js';

const temporary: string[] = [];
async function temp() { const directory = await fs.mkdtemp(path.join(os.tmpdir(), 'oods-loop-spec-')); temporary.push(directory); return directory; }
afterEach(async () => { await Promise.all(temporary.splice(0).map(directory => fs.rm(directory, { recursive: true, force: true }))); });
const hash = `sha256:${'a'.repeat(64)}`;
function receipt() {
  return { version: '1.0', framework: 'react', compose: { object: 'Subscription', context: 'list' }, schemaHash: hash, artifactContentHash: hash,
    sourceHead: 'a'.repeat(40), files: [{ path: 'src/GeneratedUI.tsx', contentHash: hash }], model: {}, steps: [], clock: '2026-09-08T12:00:00.000Z', locale: 'en-US', timezone: 'UTC',
    packages: [{ name: '@oods/components-react', version: '1.0.0', sha256: hash, installSpec: 'file:./tarballs/react.tgz' }],
    views: [{ width: 390, accessibility: '- main\n  - textbox "Search":\n', screenshot: '390.png', screenshotHash: hash, dump: '390.a11y.txt',
      measurements: { viewportWidth: 390, documentWidth: 390, elementCount: 12, overflow: [], glyphWraps: [] }, values: [], regions: [{ id: 'list-toolbar', component: 'Stack', text: 'Search' }] }],
    errors: [], timings: { composeMs: 5, generateMs: 6, captureMs: 7 }, output: '/tmp/receipt', consumer: { root: '/tmp/consumer', port: 4478, pid: 10 } };
}

describe('Design-loop observations remain evidence rather than repaired output', () => {
  it('requires hashes, errors and measurements instead of accepting an incomplete green receipt', async () => {
    await expect(validateReceipt(receipt())).resolves.toBeUndefined();
    for (const key of ['errors', 'schemaHash', 'views']) {
      const broken: any = receipt(); delete broken[key];
      await expect(validateReceipt(broken)).rejects.toThrow('Invalid design-loop receipt');
    }
    const broken = receipt(); broken.views[0]!.measurements.viewportWidth = '390' as any;
    await expect(validateReceipt(broken)).rejects.toThrow('Invalid design-loop receipt');
  });
  it('treats unchanged observations as identical across output locations and timings', () => {
    const before = receipt(), after = receipt(); after.output = '/tmp/elsewhere'; after.timings.captureMs = 400; after.views[0]!.screenshotHash = `sha256:${'b'.repeat(64)}`;
    expect(compareReceipts(before, after)).toEqual({ differenceCount: 0, differences: [] });
  });
  it('names toolbar mutations and detects both deleted source files and browser errors', () => {
    const before = receipt(), after = receipt(); after.views[0]!.regions[0]!.text = 'Search Billing summary'; after.files = [];
    (after.errors as any[]).push({ type: 'page', text: 'Render failed' });
    const delta = compareReceipts(before, after);
    expect(delta.differences.map(row => row.field)).toEqual(['errors', 'files.src/GeneratedUI.tsx', 'views.390.regions']);
    expect(JSON.stringify(delta)).toContain('list-toolbar');
    expect(JSON.stringify(delta)).toContain('Render failed');
  });
  it('does not let generated paths or symlinked outputs reach canonical inputs', async () => {
    for (const name of ['../outside.ts', '/absolute.ts', 'src/../../bad.ts', '..\\bad.ts']) expect(() => relativeFile('/tmp/consumer', name)).toThrow();
    const directory = await temp(); const store = path.join(directory, '.oods', 'schemas'); await fs.mkdir(store, { recursive: true });
    await fs.symlink(store, path.join(directory, 'alias'));
    await expect(outputDirectory(path.join(directory, 'alias', 'receipt'))).rejects.toThrow('saved store');
    await expect(outputDirectory(path.join(directory, 'artifacts', 'structured-data', 'receipt'))).rejects.toThrow('structured-data');
    await expect(outputDirectory(path.join(directory, 'receipts'))).resolves.toBe(path.join(await fs.realpath(directory), 'receipts'));
  });
  it.each(['react', 'vue'] as const)('mounts %s standalone artifacts without altering generated bytes', framework => {
    const extension = framework === 'react' ? '.tsx' : '.vue';
    const artifact = buildGeneratedArtifact({ framework, imports: [], code: 'generated contents', fileExtension: extension });
    const request = { artifact, model: { amount: 1999 } } as CaptureRequest;
    const files = consumerEntries(framework, request);
    expect(files[artifact.files[0]!.path]).toBe('generated contents');
    if (framework === 'react') expect(files['src/main.tsx']).toContain('import { GeneratedUI as Page }');
    expect(files[framework === 'react' ? 'src/main.tsx' : 'src/main.ts']).toContain('1999');
    expect(Object.values(files).join('\n')).not.toContain('workflow-records');
  });
  it('uses the workflow application exactly as generated with no parallel consumer wiring', () => {
    const artifact = buildGeneratedArtifact({ framework: 'react', imports: [], files: [{ path: 'package.json', contents: '{"private":true}' }, { path: 'src/App.tsx', contents: 'the generated app' }] });
    expect(consumerEntries('react', { artifact } as CaptureRequest)).toEqual(Object.fromEntries(artifact.files.map(file => [file.path, file.contents])));
  });
  it('reports a stopped server before creating partial render output', async () => {
    const output = path.join(await temp(), 'output');
    expect(await status(1)).toMatchObject({ running: false });
    await expect(render({ compose: { object: 'Subscription', context: 'list' }, output, port: 1 })).rejects.toThrow();
    expect(await fs.stat(output).then(() => true, () => false)).toBe(false);
  });
  it('writes a validated machine and human diff into the requested directory', async () => {
    const directory = await temp(); const before = path.join(directory, 'before.json'), after = path.join(directory, 'after.json');
    await fs.writeFile(before, JSON.stringify(receipt())); await fs.writeFile(after, JSON.stringify(receipt()));
    const output = path.join(directory, 'diff'); expect((await diff(before, after, output)).differenceCount).toBe(0);
    expect(await fs.readFile(path.join(output, 'diff.md'), 'utf8')).toContain('0 differences.');
  });
});
