import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { handle as compose } from '../../../../packages/mcp-server/src/tools/design.compose.js';
import { handle as generate } from '../../../../packages/mcp-server/src/tools/code.generate.js';
const root = path.resolve('artifacts/product-reality/sprint-198/m05');
const before = path.join(root, 'diagnostic-payment-tab');
const after = path.join(root, 'accepted');
const sourceHead = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim();
const read = async (file: string) => JSON.parse(await fs.readFile(file, 'utf8'));
const hash = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
const oldPackages = await read(path.join(before, 'submitted-packages/inventory.json'));
const packages = await read(path.join(after, 'submitted-packages/inventory.json'));
assert.deepEqual(packages, oldPackages, 'All five exact package tarballs must be unchanged');
for (const row of packages) assert.equal(hash(await fs.readFile(path.join(after, row.artifactPath))), row.sha256);
const objects = [];
for (const object of ['Organization', 'User']) {
  const composition = await compose({ object, context: 'workflow' });
  const report = await read(path.join(before, object.toLowerCase(), 'report.json'));
  const cells = [];
  for (const framework of ['react', 'vue'] as const) {
    const generated = await generate({ schema: composition.schema, framework, profile: 'build' });
    assert.equal(generated.status, 'ok');
    const original = await read(path.join(before, object.toLowerCase(), `${framework}-generation.json`));
    assert.deepEqual(generated.artifact, original.artifact, `${object}/${framework}: every generated byte and envelope field must match`);
    cells.push({ framework, artifactHash: generated.artifact!.contentHash, allArtifactFieldsEqual: true });
  }
  objects.push({ object, executionHead: report.sourceHead, currentSourceHead: sourceHead, cells });
  await fs.cp(path.join(before, object.toLowerCase()), path.join(after, object.toLowerCase()), { recursive: true, errorOnExist: true, force: false });
}
await fs.writeFile(path.join(after, 'equivalence.json'), JSON.stringify({ sourceHead, objects, packages, rationale: 'Only Subscription archival sample metadata and the payment-tab verifier changed after these passing Organization/User captures. Their complete generated artifacts and all five freshly repacked tarball hashes are byte-identical. Original execution heads remain preserved; these browsers were not re-run at the new head.', builderSelfCertified: false }, null, 2) + '\n');
console.log('Organization/User: 4 complete generated artifacts and all 5 exact package hashes unchanged; original execution heads retained.');
