import type { DomainRecord } from './store';

export const sampleData: DomainRecord[] = [
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#aria-allowed-attr",
    "title": "Elements must only use supported ARIA attributes",
    "description": "Ensure an element's role supports its ARIA attributes",
    "impact": "critical",
    "rule_id": "aria-allowed-attr",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      ".ytmVideoInfoVideoTitle",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.aria",
      "wcag2a",
      "wcag412",
      "EN-301-549",
      "EN-9.4.1.2",
      "RGAAv4",
      "RGAA-7.1.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-allowed-attr?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#aria-prohibited-attr",
    "title": "Elements must only use permitted ARIA attributes",
    "description": "Ensure ARIA attributes are not prohibited for an element's role",
    "impact": "serious",
    "rule_id": "aria-prohibited-attr",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      "#movie_player",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.aria",
      "wcag2a",
      "wcag412",
      "EN-301-549",
      "EN-9.4.1.2",
      "RGAAv4",
      "RGAA-7.1.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-prohibited-attr?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#button-name",
    "title": "Buttons must have discernible text",
    "description": "Ensure buttons have discernible text",
    "impact": "critical",
    "rule_id": "button-name",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      ".ytmVideoInfoChannelAvatar",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.name-role-value",
      "wcag2a",
      "wcag412",
      "section508",
      "section508.22.a",
      "TTv5",
      "TT6.a",
      "EN-301-549",
      "EN-9.4.1.2",
      "ACT",
      "RGAAv4",
      "RGAA-11.9.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/button-name?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/components--e49bf947.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:48:19.238Z",
    "finding_id": "/components#aria-allowed-role",
    "title": "ARIA role should be appropriate for the element",
    "description": "Ensure role attribute has an appropriate value for the element",
    "impact": "minor",
    "rule_id": "aria-allowed-role",
    "route": "/components",
    "page_url": "https://designsystem.digital.gov/components",
    "node_count": 47,
    "selectors": [
      "li[aria-label=\"Accordion\"]",
      "li[aria-label=\"Alert\"]",
      "li[aria-label=\"Banner\"]",
      "li[aria-label=\"Breadcrumb\"]",
      "li[aria-label=\"Button\"]",
      "li[aria-label=\"Button group\"]",
      "li[aria-label=\"Card\"]",
      "li[aria-label=\"Character count\"]",
      "li[aria-label=\"Checkbox\"]",
      "li[aria-label=\"Collection\"]",
      "li[aria-label=\"Combo box\"]",
      "li[aria-label=\"Data visualizations\"]",
      "li[aria-label=\"Date picker\"]",
      "li[aria-label=\"Date range picker\"]",
      "li[aria-label=\"File input\"]",
      "li[aria-label=\"Footer\"]",
      "li[aria-label=\"Form\"]",
      "li[aria-label=\"Header\"]",
      "li[aria-label=\"Icon\"]",
      "li[aria-label=\"Icon list\"]"
    ],
    "criteria": [
      "cat.aria",
      "best-practice"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-allowed-role?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/components_banner--60c71ed2.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:49:30.540Z",
    "finding_id": "/components/banner#landmark-unique",
    "title": "Landmarks should have a unique role or role/label/title (i.e. accessible name) combination",
    "description": "Ensure landmarks are unique",
    "impact": "moderate",
    "rule_id": "landmark-unique",
    "route": "/components/banner",
    "page_url": "https://designsystem.digital.gov/components/banner",
    "node_count": 2,
    "selectors": [
      "#banner--default-preview-content > .usa-banner:nth-child(2)",
      ".usa-banner:nth-child(6)"
    ],
    "criteria": [
      "cat.semantics",
      "best-practice"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/landmark-unique?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/components_data-visualizations--df1931f8.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:51:01.072Z",
    "finding_id": "/components/data-visualizations#empty-table-header",
    "title": "Table header text should not be empty",
    "description": "Ensure table headers have discernible text",
    "impact": "minor",
    "rule_id": "empty-table-header",
    "route": "/components/data-visualizations",
    "page_url": "https://designsystem.digital.gov/components/data-visualizations",
    "node_count": 1,
    "selectors": [
      "table[aria-describedby=\"source_line\"] > thead > tr > th[scope=\"col\"]:nth-child(1)"
    ],
    "criteria": [
      "cat.name-role-value",
      "best-practice"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/empty-table-header?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#aria-allowed-attr",
    "title": "Elements must only use supported ARIA attributes",
    "description": "Ensure an element's role supports its ARIA attributes",
    "impact": "critical",
    "rule_id": "aria-allowed-attr",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      ".ytmVideoInfoVideoTitle",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.aria",
      "wcag2a",
      "wcag412",
      "EN-301-549",
      "EN-9.4.1.2",
      "RGAAv4",
      "RGAA-7.1.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-allowed-attr?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#aria-prohibited-attr",
    "title": "Elements must only use permitted ARIA attributes",
    "description": "Ensure ARIA attributes are not prohibited for an element's role",
    "impact": "serious",
    "rule_id": "aria-prohibited-attr",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      "#movie_player",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.aria",
      "wcag2a",
      "wcag412",
      "EN-301-549",
      "EN-9.4.1.2",
      "RGAAv4",
      "RGAA-7.1.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-prohibited-attr?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/about_monthly-calls--5f548cfd.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:46:39.300Z",
    "finding_id": "/about/monthly-calls#button-name",
    "title": "Buttons must have discernible text",
    "description": "Ensure buttons have discernible text",
    "impact": "critical",
    "rule_id": "button-name",
    "route": "/about/monthly-calls",
    "page_url": "https://designsystem.digital.gov/about/monthly-calls",
    "node_count": 21,
    "selectors": [
      ".usa-embed-container.margin-top-4:nth-child(9) > iframe",
      ".ytmVideoInfoChannelAvatar",
      ".usa-embed-container.margin-top-4:nth-child(14) > iframe",
      "iframe[title=\"Engineering values\"]",
      ".usa-embed-container.margin-top-4:nth-child(24) > iframe",
      "iframe[title=\"A look at beta Web Components\"]",
      ".usa-embed-container.margin-top-4:nth-child(34) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(39) > iframe",
      "iframe[title=\"Introduction to Web Components\"]",
      "iframe[title=\"Building with USWDS tools\"]",
      "iframe[title=\"USWDS component lifecycle\"]",
      ".usa-embed-container.margin-top-4:nth-child(59) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(64) > iframe",
      ".usa-embed-container.margin-top-4:nth-child(69) > iframe",
      "iframe[title=\"Mission, vision, and polestar\"]",
      "iframe[title=\"Product roadmap\"]",
      ".usa-embed-container.margin-top-4:nth-child(84) > iframe",
      "iframe[title=\"Real-world accessibility\"]",
      "iframe[title=\"Top tasks\"]",
      ".usa-embed-container.margin-top-4:nth-child(99) > iframe"
    ],
    "criteria": [
      "cat.name-role-value",
      "wcag2a",
      "wcag412",
      "section508",
      "section508.22.a",
      "TTv5",
      "TT6.a",
      "EN-301-549",
      "EN-9.4.1.2",
      "ACT",
      "RGAAv4",
      "RGAA-11.9.1"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/button-name?application=playwright"
  },
  {
    "searchQuery": "",
    "searchActive": false,
    "filters": [],
    "activeFilters": [],
    "filterCount": 0,
    "page": 1,
    "pageSize": 25,
    "totalItems": 0,
    "totalPages": 0,
    "result_state": "violation",
    "provenance_source": "Stage1",
    "provenance_record": "6e435ce7-eaab-46b4-be6b-cea9b80defa6",
    "provenance_locator": "evidence/a11y/components--e49bf947.json",
    "provenance_method": "axe-core 4.11.0",
    "provenance_at": "2026-09-17T00:48:19.238Z",
    "finding_id": "/components#aria-allowed-role",
    "title": "ARIA role should be appropriate for the element",
    "description": "Ensure role attribute has an appropriate value for the element",
    "impact": "minor",
    "rule_id": "aria-allowed-role",
    "route": "/components",
    "page_url": "https://designsystem.digital.gov/components",
    "node_count": 47,
    "selectors": [
      "li[aria-label=\"Accordion\"]",
      "li[aria-label=\"Alert\"]",
      "li[aria-label=\"Banner\"]",
      "li[aria-label=\"Breadcrumb\"]",
      "li[aria-label=\"Button\"]",
      "li[aria-label=\"Button group\"]",
      "li[aria-label=\"Card\"]",
      "li[aria-label=\"Character count\"]",
      "li[aria-label=\"Checkbox\"]",
      "li[aria-label=\"Collection\"]",
      "li[aria-label=\"Combo box\"]",
      "li[aria-label=\"Data visualizations\"]",
      "li[aria-label=\"Date picker\"]",
      "li[aria-label=\"Date range picker\"]",
      "li[aria-label=\"File input\"]",
      "li[aria-label=\"Footer\"]",
      "li[aria-label=\"Form\"]",
      "li[aria-label=\"Header\"]",
      "li[aria-label=\"Icon\"]",
      "li[aria-label=\"Icon list\"]"
    ],
    "criteria": [
      "cat.aria",
      "best-practice"
    ],
    "help_url": "https://dequeuniversity.com/rules/axe/4.11/aria-allowed-role?application=playwright"
  }
];
